

import argparse
import traceback
import re
import pandas as pd
import numpy as np
import subprocess
import os
import shutil
import pysam
from collections import defaultdict
import io
import concurrent.futures
import time
from math import ceil

# Pipeline: read VCFs -> merge into one variants df -> annotate (gnomAD, ClinVar, ANNOVAR, CADD, SpliceAI -> write {outprefix}_compiled_variants.tsv.
def parse_args():
    parser = argparse.ArgumentParser(
        description="Compile variants from multiple VCF files and add annotations "
                    "(gnomAD, ClinVar, Annovar, CADD, SpliceAI) into a single .tsv file "
                    "({outprefix}_compiled_variants.tsv). "
                    "Note that contigs in all VCF and BED files should be formatted as "
                    "'chr1', 'chr2', ..., 'chrX', 'chrY', 'chrM'. "
                    "Also note that insertions should be formatted as A>ATC (rather than ->TC), "
                    "deletions as AAAGT>A (rather than AAGT>-), and SNVs as A>T for compatibility "
                    "with CLINVAR and gnomAD VCF files.")
    parser.add_argument("--vcf-files", required=True, nargs="+", help="Paths to VCF files")
    parser.add_argument('--vcf-file-names', nargs="+",
        help="Names of VCF files. If not provided, the file name will be used.")
    parser.add_argument("--outprefix", required=True,
        help="Output prefix (including path, not including file extension)")
    parser.add_argument("--sample-name", required=True,
        help="Sample identifier, stamped into a 'sample' column in the output tsv(s) "
             "so downstream cross-sample merging doesn't need to add it separately.")
    parser.add_argument("--bed",
        help="Path to BED file. If provided, only variants in the BED file will be compiled.")
    parser.add_argument("--genome",
        help="Path to FASTA file for the reference genome. Required if --ANNOVAR or --SpliceAI is used.")
    parser.add_argument("--gtf",
        help="Path to GTF file to build SpliceAI's gene annotation from"
             "If --include-SpliceAI-scores is used and no GTF is provided, falls "
             "back to SpliceAI's own bundled annotation, selected via --SpliceAI-annotation.")
    parser.add_argument("--gnomad-vcf",
        help="Path to gnomAD VCF file(s). If provided, maximum gnomAD allele frequencies will be "
             "included in the final output. If multiple VCF files are provided, they should be "
             "provided as a comma-separated list (e.g. --gnomad-vcf 'gnomad.vcf.gz,gnomad2.vcf.gz').")
    parser.add_argument("--gnomad-vcf-fallback",
        help="Comma-separated gnomAD VCF file(s)/URL(s) to retry against if --gnomad-vcf fails "
             "for any reason at runtime. Typically the canonical public gnomAD URLs, so a broken/missing local "
             "install doesn't halt the pipeline. If omitted, or identical to --gnomad-vcf, no second attempt is made.")
    parser.add_argument("--clinvar-vcf",
        help="Path to ClinVar VCF file. If provided, CLNSIG annotations will be included in the final output.")
    parser.add_argument("--clinvar-vcf-fallback",
        help="ClinVar VCF file/URL to retry against if --clinvar-vcf fails for any reason at "
             "runtime (see --gnomad-vcf-fallback). If omitted, or identical to --clinvar-vcf, "
             "no second attempt is made.")
    parser.add_argument("--ANNOVAR-dir",
        help="Path to Annovar directory. If provided, Annovar gene annotations "
             "(Func, Gene, GeneDetail, ExonicFunc, AAChange) will be included in the final output.")
    parser.add_argument("--CADD-script",
        help="Path to an executable that runs CADD-scripts' CADD.sh in conda-only mode "
             "(CADD.sh -m -- see setup_resources.sh's CADD-scripts install section) rather than "
             "a Singularity container. Normally CADD_wrapper.sh (generated by setup_resources.sh "
             "alongside CADD.sh, at resources/CADD-scripts-1.7.1/CADD_wrapper.sh) rather than "
             "CADD.sh itself -- the wrapper takes care of environment-specific setup (e.g. "
             "making a suitable `snakemake` available on PATH for CADD.sh's own internal "
             "`snakemake --sdm conda ...` call, without leaking unrelated tooling that could "
             "confuse CADD.sh's own per-rule conda environments) so this script doesn't need to "
             "know anything about it. If provided (non-empty), a local CADD run is attempted "
             "first. If omitted/empty, or if the local run fails at runtime, falls back to "
             "--CADD-local-prescored-snv/--CADD-local-prescored-indel, then to "
             "--CADD-prescored-url (see below).")
    parser.add_argument("--CADD-data-dir",
        help="Path to CADD-scripts' downloaded annotation/prescored data directory "
             "(resources/CADD-scripts-1.7.1/data). Expected to live alongside --CADD-script "
             "as CADD-scripts' own <install_dir>/data (CADD.sh finds it relative to itself), "
             "so this is only used to sanity-check the install before running. Required if "
             "--CADD-script is given.")
    parser.add_argument("--CADD-local-prescored-snv",
        help="Path to CADD-scripts' downloaded local pre-scored whole-genome SNV file "
             "(resources/CADD-scripts-1.7.1/data/prescored/GRCh38_v1.7/no_anno/"
             "whole_genome_SNVs.tsv.gz, bgzip+tabix-indexed), queried locally and restricted "
             "to the variant positions being compiled -- covers SNVs only (not InDels). Used "
             "as the CADD source whenever --CADD-script isn't provided, or if a local CADD run "
             "is attempted but fails at runtime. Falls back to --CADD-prescored-url if this "
             "isn't provided, or if this lookup fails at runtime.")
    parser.add_argument("--CADD-local-prescored-indel",
        help="Path to CADD-scripts' downloaded local pre-scored gnomAD InDel file "
             "(resources/CADD-scripts-1.7.1/data/prescored/GRCh38_v1.7/no_anno/"
             "gnomad.genomes.r4.0.indel.tsv.gz, bgzip+tabix-indexed), queried locally, "
             "alongside --CADD-local-prescored-snv, whenever that stage runs -- see above. "
             "InDels get a CADD_PHRED of '.' if this isn't provided, since "
             "--CADD-prescored-url has no InDel coverage to fall back to either.")
    parser.add_argument("--CADD-prescored-url",
        help="URL to CADD's public pre-scored whole-genome SNV file (bgzip+tabix-indexed), "
             "queried remotely and restricted to the variant positions being compiled -- "
             "covers SNVs only (not InDels). Used as the last-resort CADD source: whenever "
             "--CADD-script isn't provided and neither --CADD-local-prescored-snv nor "
             "--CADD-local-prescored-indel is provided either, or if a local CADD run and/or "
             "the local pre-scored lookup are attempted but fail at runtime. Any InDel gets a "
             "CADD_PHRED of '.' whenever this ends up being the source actually used, since "
             "there's no remote InDel lookup.")
    parser.add_argument("--include-CADD-annotations", action='store_true',
        help="Include CADD annotations in the final output. Note: there are >100 columns of CADD annotations, so use caution.")
    parser.add_argument("--CADD-gnomadAF-threshold", type=float, default=1,
        help="Allele frequency threshold for CADD analysis (only run CADD on variants with max "
             "gnomad AF below this threshold, or unknown/'.').")
    parser.add_argument("--CADD-CLNSIG-filter", nargs="+",
        help="CLNSIG values to exclude from CADD analysis (ex: Benign, Likely_benign, Benign/Likely_benign).")
    parser.add_argument("--SpliceAI-gnomadAF-threshold", type=float, default=1,
        help="Allele frequency threshold for SpliceAI analysis (only run SpliceAI on variants "
             "with max gnomad AF below this threshold, or unknown/'.'). Independent of "
             "--CADD-gnomadAF-threshold -- set both to the same value to keep CADD and SpliceAI "
             "scoring the same variant subset, or different values to filter each independently.")
    parser.add_argument("--SpliceAI-CLNSIG-filter", nargs="+",
        help="CLNSIG values to exclude from SpliceAI analysis (ex: Benign, Likely_benign, "
             "Benign/Likely_benign). Independent of --CADD-CLNSIG-filter (see above).")
    parser.add_argument("--include-SpliceAI-scores", action='store_true',
        help="Include SpliceAI scores in the final output. Runs the actual spliceai tool "
             "(bioconda/pip package) on the variant set first, if --genome is provided -- "
             "practical because by this point in the pipeline the variant set is small "
             "(a targeted panel's worth, post gnomAD/ClinVar/ANNOVAR/CADD), not genome-wide. "
             "If --genome isn't provided, or the live run fails at runtime, falls back to "
             "--SpliceAI-prescored-snv-vcf/--SpliceAI-prescored-indel-vcf instead -- see those "
             "flags.")
    parser.add_argument("--SpliceAI-annotation", choices=['grch37', 'grch38'], default='grch38',
        help="SpliceAI annotation version to use if --gtf is not provided (default: grch38). "
             "If --gtf IS provided, that takes precedence over this. Only used for live "
             "scoring -- has no effect if a prescored VCF lookup is used instead (see below).")
    parser.add_argument("--SpliceAI-prescored-snv-vcf", default=None,
        help="Path or URL to a bgzip+tabix-indexed VCF of precomputed SpliceAI SNV scores "
             "(e.g. Illumina's spliceai_scores.masked.snv.hg38.vcf.gz -- see "
             "setup_resources.sh). Used as the SpliceAI source whenever --genome isn't "
             "provided, or if a live spliceai run is attempted but fails at runtime -- SNVs "
             "are looked up here, InDels are looked up in --SpliceAI-prescored-indel-vcf. If "
             "one of the two isn't given while the other is, that variant type gets '.' (no "
             "fallback for just the missing one -- by design, to keep results consistent "
             "within a run).")
    parser.add_argument("--SpliceAI-prescored-indel-vcf", default=None,
        help="Path or URL to a bgzip+tabix-indexed VCF of precomputed SpliceAI InDel scores "
             "(e.g. Illumina's spliceai_scores.masked.indel.hg38.vcf.gz). See "
             "--SpliceAI-prescored-snv-vcf for how this and that flag interact.")
    parser.add_argument("--SpliceAI-force-prescored-lookup", action='store_true',
        help="Skip the live spliceai run entirely, even if --genome is provided, and go "
             "straight to the prescored VCF lookup (--SpliceAI-prescored-snv-vcf/"
             "--SpliceAI-prescored-indel-vcf). Without this flag, live scoring is always "
             "attempted first if --genome is given, and the prescored VCFs are only used as a "
             "fallback if that live run fails at runtime -- this flag is for cases where you'd "
             "rather always skip the (slower, TensorFlow-based) live run outright, e.g. to save "
             "compute time when the prescored files are known to already cover your variant set. "
             "Has no effect if neither prescored VCF is provided -- falls through to '.' the "
             "same as an unconfigured, failed live run would.")
    parser.add_argument("--threads", type=int, default=1,
        help="Number of threads to use (for running CADD and SpliceAI).")
    return parser.parse_args()


# Convert a GTF to the exon-list format SpliceAI's live scorer expects for a custom annotation
def process_gtf(gtf, outfile):
    df = pd.read_csv(gtf, sep='\t', comment='#',
                     names=["CHROM", "SOURCE", "FEATURE", "START", "END", "SCORE", "STRAND", "FRAME", "ATTRIBUTES"])
    df = df[df['FEATURE'] == 'exon']
    df['TRANSCRIPT_ID'] = df['ATTRIBUTES'].str.extract('transcript_id "(.*?)"')
    df = df[['CHROM', 'STRAND', 'START', 'END', 'TRANSCRIPT_ID']]
    df['START'] = df['START'].astype(int) - 1
    grouped_df = df.groupby(['TRANSCRIPT_ID', 'CHROM', 'STRAND'])
    output_df = grouped_df.agg(
        TX_START=('START', 'min'),
        TX_END=('END', 'max'),
        EXON_START=('START', lambda x: ','.join(map(str, sorted(x))) + ','),
        EXON_END=('END', lambda x: ','.join(map(str, sorted(x))) + ',')
    )
    output_df.reset_index(inplace=True)
    output_df.rename(columns={'TRANSCRIPT_ID': '#NAME'}, inplace=True)
    output_df.to_csv(outfile, sep='\t', index=False)


# Stream a remote VCF through bcftools view | query, retrying with backoff on transient failures
def _run_remote_bcftools_pipeline(view_cmd, query_cmd, max_retries=5, initial_delay=15, cwd=None, label=None,
                                   quiet_success=False):
    tag = f' ({label})' if label else ''
    delay = initial_delay
    last_err = ''
    for attempt in range(1, max_retries + 1):
        view_proc = subprocess.Popen(view_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
        query_proc = subprocess.Popen(
            query_cmd, stdin=view_proc.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            universal_newlines=True, cwd=cwd)
        view_proc.stdout.close()
        query_out, query_err = query_proc.communicate()
        view_err = view_proc.stderr.read().decode(errors='replace') if view_proc.stderr else ''
        view_proc.wait()

        if view_proc.returncode == 0 and query_proc.returncode == 0:
            if not quiet_success:
                print(f'  Succeeded{tag} on attempt {attempt}/{max_retries}.')
            return query_out

        last_err = (view_err or query_err or '').strip()
        short_err = last_err.splitlines()[-1] if last_err else 'unknown error'
        if attempt < max_retries:
            print(f'  Remote VCF stream failed{tag} (attempt {attempt}/{max_retries}): {short_err}. '
                  f'Retrying in {delay}s...')
            time.sleep(delay)
            delay *= 2
        else:
            print(f'  Remote VCF stream failed{tag} (attempt {attempt}/{max_retries}): {short_err}. Giving up.')

    raise RuntimeError(
        f'bcftools failed after {max_retries} attempts while streaming remote VCF '
        f'({" ".join(view_cmd)}): {last_err}')


# Fetch a remote VCF's header, retrying with backoff on transient failures
def _bcftools_header_with_retry(vcf_file, max_retries=5, initial_delay=15, cwd=None):
    delay = initial_delay
    last_err = None
    for attempt in range(1, max_retries + 1):
        try:
            return subprocess.check_output(["bcftools", "view", "-h", vcf_file], text=True, cwd=cwd)
        except subprocess.CalledProcessError as e:
            last_err = e
            if attempt < max_retries:
                print(f'  Fetching header failed (attempt {attempt}/{max_retries}). Retrying in {delay}s...')
                time.sleep(delay)
                delay *= 2
    raise last_err


# Run tabix against a remote indexed file, retrying with backoff on transient failures
def _run_remote_tabix_with_retry(url, extra_args, max_retries=5, initial_delay=15, cwd=None, label=None):
    tag = f' ({label})' if label else ''
    cmd = ['tabix', url] + list(extra_args)
    delay = initial_delay
    last_err = ''
    for attempt in range(1, max_retries + 1):
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               universal_newlines=True, cwd=cwd)
        if proc.returncode == 0:
            print(f'  Succeeded{tag} on attempt {attempt}/{max_retries}.')
            return proc.stdout
        last_err = (proc.stderr or '').strip()
        short_err = last_err.splitlines()[-1] if last_err else 'unknown error'
        if attempt < max_retries:
            print(f'  Remote tabix query failed{tag} (attempt {attempt}/{max_retries}): {short_err}. '
                  f'Retrying in {delay}s...')
            time.sleep(delay)
            delay *= 2
        else:
            print(f'  Remote tabix query failed{tag} (attempt {attempt}/{max_retries}): {short_err}. Giving up.')
    raise RuntimeError(f'tabix failed after {max_retries} attempts while querying {url}: {last_err}')


def _is_remote_url(path):
    return re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', path) is not None


# Query a VCF (local or remote) restricted to a BED's regions; remote files are chunked and
# queried in parallel to dodge a libcurl HTTP/2 bug from too many requests on one connection
def _query_vcf_regions(vcf_file, bed_file, format_string, threads, cwd, chunk_size=10, max_workers=None):
    if max_workers is None:
        max_workers = threads

    view_base_cmd = ['bcftools', 'view', '--threads', str(threads)]
    query_cmd = ['bcftools', 'query', '-f', format_string]

    if not _is_remote_url(vcf_file):
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=None, quiet_success=True)

    os.makedirs(cwd, exist_ok=True)

    if not chunk_size:
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=cwd)

    with open(bed_file) as fh:
        regions = sorted(set(line for line in fh if line.strip()))

    if len(regions) <= chunk_size:
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=cwd)

    chunks = [regions[i:i + chunk_size] for i in range(0, len(regions), chunk_size)]
    n_chunks = len(chunks)
    print(f'  {len(regions)} unique regions against a remote file -- querying in '
          f'{n_chunks} chunk(s) of {chunk_size} region(s) each, up to {max_workers} at a '
          f'time, to avoid a known libcurl HTTP/2 bug triggered by too many requests on '
          f'one persistent connection.')

    chunk_view_cmd = ['bcftools', 'view', '--threads', '1']

    def _query_chunk(chunk_num, chunk_regions):
        chunk_bed = os.path.join(cwd, f'_region_chunk_{chunk_num}.bed')
        with open(chunk_bed, 'w') as fh:
            fh.writelines(chunk_regions)
        return chunk_num, _run_remote_bcftools_pipeline(
            chunk_view_cmd + ['-R', chunk_bed, vcf_file], query_cmd, cwd=cwd,
            label=f'chunk {chunk_num}/{n_chunks}')

    results = {}
    completed = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(_query_chunk, i + 1, chunk): i + 1
            for i, chunk in enumerate(chunks)
        }
        for future in concurrent.futures.as_completed(futures):
            chunk_num, stdout = future.result()
            results[chunk_num] = stdout
            completed += 1
            if completed % max(1, n_chunks // 10) == 0 or completed == n_chunks:
                print(f'  Completed {completed}/{n_chunks} chunks...')

    return ''.join(results[i + 1] for i in range(n_chunks))


# Pull non-hom-ref, non-missing genotypes out of one VCF into a dict keyed by variant identity
def process_vcf(vcf_file, vcf_file_name, bed_file, genome):

    vcf_data = {}

    if not os.path.isfile(vcf_file):
        print(f'\nWARNING: VCF file {vcf_file} does not exist. Skipping...')
        return vcf_data

    if bed_file:
        command = ['bcftools', 'view', '-H', '-R', bed_file, '-e', 'GT="0/0" || GT="./."', vcf_file]
    else:
        command = ['bcftools', 'view', '-H', '-e', 'GT="0/0" || GT="./."', vcf_file]
    result = subprocess.run(command, stdout=subprocess.PIPE, universal_newlines=True, check=True)
    lines = result.stdout.split('\n')

    for line in lines[:-1]:
        fields = line.split('\t')
        chrom, pos, _, ref, alt, qual, filt, info, form, genotype = (f.strip() for f in fields[:10])
        format_keys = form.split(':')
        genotype_values = genotype.split(':')
        format_dict = dict(zip(format_keys, genotype_values))
        gt = format_dict.get('GT', '.')
        dp = format_dict.get('DP', '.')
        af = format_dict.get('VAF') or format_dict.get('AF') or '.'
        ps = format_dict.get('PS', '.')
        vcf_data[(vcf_file_name, chrom, pos, ref, alt)] = [qual, filt, info, form, genotype, gt, dp, af, ps]

    print(f'\nFinished processing {len(vcf_data)} variants from {vcf_file}.')
    return vcf_data


# Annotate max gnomAD AF per variant (AF_grpmax > AF_hom > AF, whichever the VCF has); falls
# back to gnomad_vcf_fallback on failure, then to 'fail' for all variants if that fails too
def extract_gnomAD_AF(df, gnomad_vcf, outprefix, bed_file, threads, cache_dir, gnomad_vcf_fallback=None):

    start_time = time.time()

    def is_remote(path):
        return re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', path) is not None

    def _attempt(gnomad_vcf_value):
        nonlocal df

        for gnomad_vcf_file in gnomad_vcf_value.split(','):
            gnomad_vcf_file = gnomad_vcf_file.strip()
            if is_remote(gnomad_vcf_file):
                continue
            if not os.path.isfile(gnomad_vcf_file):
                raise FileNotFoundError(f'gnomAD VCF file {gnomad_vcf_file} not found.')
            if not os.path.isfile(f'{gnomad_vcf_file}.csi') and not os.path.isfile(f'{gnomad_vcf_file}.tbi'):
                raise FileNotFoundError(f'gnomAD VCF file {gnomad_vcf_file} is not indexed.')

        af_chunks = []
        for gnomad_vcf_file in gnomad_vcf_value.split(','):
            gnomad_vcf_file = gnomad_vcf_file.strip()
            print(f'\nProcessing gnomAD VCF file: {gnomad_vcf_file}')
            print(f'  Extracting gnomAD allele frequencies from gnomAD VCF. This may take a few minutes...')

            file_is_remote = is_remote(gnomad_vcf_file)
            file_cwd = None
            if file_is_remote:
                os.makedirs(cache_dir, exist_ok=True)
                file_cwd = cache_dir

            header = _bcftools_header_with_retry(gnomad_vcf_file, cwd=file_cwd)
            if "ID=AF_grpmax" in header:
                af_tag = "AF_grpmax"
            elif "ID=AF_hom" in header:
                af_tag = "AF_hom"
            elif "ID=AF" in header:
                af_tag = "AF"
            else:
                print(f'  No AF field found in {gnomad_vcf_file}, skipping')
                continue

            format_string = f'%CHROM\t%POS\t%REF\t%ALT\t%INFO/{af_tag}\n'
            query_stdout = _query_vcf_regions(gnomad_vcf_file, bed_file, format_string, threads, cache_dir)
            af_df_subset = pd.read_csv(
                io.StringIO(query_stdout),
                sep='\t', header=None,
                names=['chrom', 'pos', 'ref', 'alt', 'gnomAD_AF'], dtype=str)

            def _parse_af_series(series):
                s = series.where(series != '.', other=np.nan)
                s = s.str.split(',').str[0]
                return pd.to_numeric(s, errors='coerce')

            af_df_subset['gnomAD_AF'] = _parse_af_series(af_df_subset['gnomAD_AF'])
            if not af_df_subset.empty:
                af_chunks.append(af_df_subset)

        if af_chunks:
            af_df = pd.concat(af_chunks, ignore_index=True)
            af_df = af_df.groupby(['chrom', 'pos', 'ref', 'alt'], as_index=False)['gnomAD_AF'].max()
            df = df.merge(af_df[['chrom', 'pos', 'ref', 'alt', 'gnomAD_AF']],
                          on=['chrom', 'pos', 'ref', 'alt'], how='left')
        df['gnomAD_AF'] = df['gnomAD_AF'].fillna('.').astype(str) if 'gnomAD_AF' in df.columns else '.'

    try:
        _attempt(gnomad_vcf)
    except Exception as e:
        print(f'\nWARNING: gnomAD annotation failed ({e}).')
        traceback.print_exc()
        if gnomad_vcf_fallback and gnomad_vcf_fallback.strip() != gnomad_vcf.strip():
            print(f'  Retrying against fallback source: {gnomad_vcf_fallback}\n')
            try:
                _attempt(gnomad_vcf_fallback)
            except Exception as e2:
                print(f'\nWARNING: gnomAD fallback also failed ({e2}). '
                      f'Filling gnomAD_AF with "fail" for all variants and continuing.\n')
                traceback.print_exc()
                df['gnomAD_AF'] = 'fail'
        else:
            print(f'  No (different) fallback source available. '
                  f'Filling gnomAD_AF with "fail" for all variants and continuing.\n')
            df['gnomAD_AF'] = 'fail'

    if os.path.exists(outprefix + '_compiled_variants.tsv'):
        os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    print(f'\ngnomAD allele frequencies extracted for {df[df["gnomAD_AF"] != "."].shape[0]} '
          f'variants from gnomAD VCF in {time.time() - start_time:.2f} seconds.\n')
    return df


# Annotate ClinVar CLNSIG (appending CLNSIGCONF when present); same fallback-then-'fail' pattern
# as extract_gnomAD_AF
def extract_CLNSIG(df, clinvar_vcf, outprefix, bed_file, threads, cache_dir, clinvar_vcf_fallback=None):

    start_time = time.time()

    clinvar_bed_file = outprefix + '_clinvar_lookup_positions.bed'
    clinvar_bed_df = pd.read_csv(bed_file, sep='\t', header=None, names=['chrom', 'start', 'end'], dtype=str)
    clinvar_bed_df['chrom'] = clinvar_bed_df['chrom'].str.replace(r'^chr', '', regex=True)
    clinvar_bed_df.to_csv(clinvar_bed_file, sep='\t', index=False, header=False)

    def _attempt(clinvar_vcf_value):
        nonlocal df

        if not re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', clinvar_vcf_value):
            if not os.path.isfile(clinvar_vcf_value):
                raise FileNotFoundError(f'ClinVar VCF file {clinvar_vcf_value} not found.')
            if not os.path.isfile(f'{clinvar_vcf_value}.csi') and not os.path.isfile(f'{clinvar_vcf_value}.tbi'):
                raise FileNotFoundError(f'ClinVar VCF file {clinvar_vcf_value} is not indexed.')

        print(f'\nExtracting ClinVar CLNSIG annotations from ClinVar VCF. This may take a few minutes...')
        format_string = '%CHROM\t%POS\t%REF\t%ALT\t%INFO/CLNSIG\t%INFO/CLNSIGCONF\n'
        query_stdout = _query_vcf_regions(clinvar_vcf_value, clinvar_bed_file, format_string, threads, cache_dir,
                                           chunk_size=None)

        clnsig_df = pd.read_csv(
            io.StringIO(query_stdout),
            sep='\t', header=None,
            names=['chrom', 'pos', 'ref', 'alt', 'CLNSIG', 'CLNSIGCONF'], dtype=str)
        clnsig_df['chrom'] = 'chr' + clnsig_df['chrom'].astype(str)
        clnsig_df['CLNSIG'] = np.where(
            clnsig_df['CLNSIGCONF'].notna() & (clnsig_df['CLNSIGCONF'] != '.'),
            clnsig_df['CLNSIG'] + ':' + clnsig_df['CLNSIGCONF'],
            clnsig_df['CLNSIG']
        )
        df = df.merge(clnsig_df[['chrom', 'pos', 'ref', 'alt', 'CLNSIG']],
                      on=['chrom', 'pos', 'ref', 'alt'], how='left')
        df['CLNSIG'] = df['CLNSIG'].fillna('.').astype(str)

    try:
        _attempt(clinvar_vcf)
    except Exception as e:
        print(f'\nWARNING: ClinVar annotation failed ({e}).')
        traceback.print_exc()
        if clinvar_vcf_fallback and clinvar_vcf_fallback.strip() != clinvar_vcf.strip():
            print(f'  Retrying against fallback source: {clinvar_vcf_fallback}\n')
            try:
                _attempt(clinvar_vcf_fallback)
            except Exception as e2:
                print(f'\nWARNING: ClinVar fallback also failed ({e2}). '
                      f'Filling CLNSIG with "fail" for all variants and continuing.\n')
                traceback.print_exc()
                df['CLNSIG'] = 'fail'
        else:
            print(f'  No (different) fallback source available. '
                  f'Filling CLNSIG with "fail" for all variants and continuing.\n')
            df['CLNSIG'] = 'fail'

    if os.path.exists(outprefix + '_compiled_variants.tsv'):
        os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    print(f'ClinVar CLNSIG annotations extracted for {df[df["CLNSIG"] != "."].shape[0]} '
          f'variants from ClinVar VCF in {time.time() - start_time:.2f} seconds.\n')
    return df


# Label each variant with the panel gene(s) whose BED region it falls in ('.' if none/no BED)
def add_gene_overlap_column(df, panel_bed):
    if not panel_bed:
        df['gene'] = '.'
        return df

    genes_by_chrom = defaultdict(list)
    with open(panel_bed) as fh:
        for line in fh:
            fields = line.rstrip('\n').split('\t')
            chrom, start, end, gene = fields[0], int(fields[1]), int(fields[2]), fields[3]
            genes_by_chrom[chrom].append((start, end, gene))

    def genes_at(chrom, pos):
        hits = [gene for start, end, gene in genes_by_chrom.get(chrom, []) if start < pos <= end]
        return ','.join(hits) if hits else '.'

    df['gene'] = [genes_at(chrom, int(pos)) for chrom, pos in zip(df['chrom'], df['pos'])]
    return df


# Run ANNOVAR's refGene annotation (Func/Gene/GeneDetail/ExonicFunc/AAChange); ANNOVAR's own
# indel coordinate convention is corrected back to VCF-style (A>ATC etc.) using the reference
# FASTA before merging back in. Fills all ANNOVAR columns with 'fail' if anything goes wrong.
def run_ANNOVAR(df, outprefix, ANNOVAR_dir, genome):

    ANNOVAR_COLUMNS = [
        'ANNOVAR_Func.refGene', 'ANNOVAR_Gene.refGene', 'ANNOVAR_GeneDetail.refGene',
        'ANNOVAR_ExonicFunc.refGene', 'ANNOVAR_AAChange.refGene',
    ]

    try:
        ANNOVAR_outdir = os.path.join(os.path.dirname(outprefix), 'ANNOVAR')
        os.makedirs(ANNOVAR_outdir, exist_ok=True)
        print(f'\nMaking a VCF file with all variants for Annovar analysis...')
        variants = set(map(tuple, df[['chrom', 'pos', 'ref', 'alt']].values.tolist()))
        with open(os.path.join(ANNOVAR_outdir, 'compiled_variants.vcf'), 'w') as f:
            f.write('##fileformat=VCFv4.2\n')
            unique_contig = {chrom for chrom, _, _, _ in variants}
            for contig in unique_contig:
                f.write(f'##contig=<ID={contig}>\n')
            f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
            for chrom, pos, ref, alt in variants:
                f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')

        print(f'\nRunning Annovar on compiled variants...')
        log_file = os.path.join(ANNOVAR_outdir, 'ANNOVAR.log')
        with open(log_file, 'w') as log:
            subprocess.run(
                ['perl', os.path.join(ANNOVAR_dir, 'convert2annovar.pl'), '--format', 'vcf4',
                 os.path.join(ANNOVAR_outdir, 'compiled_variants.vcf'),
                 '--outfile', os.path.join(ANNOVAR_outdir, 'compiled_variants.avinput')],
                stdout=log, stderr=log, check=True)
            subprocess.run(
                ['perl', os.path.join(ANNOVAR_dir, 'table_annovar.pl'),
                 os.path.join(ANNOVAR_outdir, 'compiled_variants.avinput'),
                 os.path.join(ANNOVAR_dir, 'humandb'),
                 '-buildver', 'hg38', '-out', os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR'),
                 '-remove', '-protocol', 'refGene', '-operation', 'g', '-nastring', '.', '-csvout'],
                stdout=log, stderr=log, check=True)

        pysam_genome = pysam.FastaFile(genome)
        corrected_path = os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR.hg38_multianno_corrected.csv')
        with open(os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR.hg38_multianno.csv'), 'r') as f, \
             open(corrected_path, 'w') as f2:
            for i, line in enumerate(f):
                if i == 0:
                    f2.write(line)
                    continue
                parts = line.strip().split(',')
                chrom, start, end, ref, alt = parts[0:5]
                if ref == '-':
                    pos = int(start)
                    ref = pysam_genome.fetch(chrom, pos - 1, pos)
                    alt = ref + alt
                elif alt == '-':
                    pos = int(start) - 1
                    alt = pysam_genome.fetch(chrom, pos - 1, pos)
                    ref = pysam_genome.fetch(chrom, pos - 1, pos + (int(end) - int(start)) + 1)
                else:
                    pos = int(start)
                f2.write(f'{chrom},{pos},{end},{ref},{alt},' + ','.join(parts[5:]) + '\n')

        df_ANNOVAR = pd.read_csv(corrected_path, sep=',')
        df_ANNOVAR = df_ANNOVAR.add_prefix('ANNOVAR_')
        df_ANNOVAR['ANNOVAR_Start'] = df_ANNOVAR['ANNOVAR_Start'].astype(str)
        df['pos'] = df['pos'].astype(str)
        df = df.merge(df_ANNOVAR, left_on=['chrom', 'pos', 'ref', 'alt'],
                      right_on=['ANNOVAR_Chr', 'ANNOVAR_Start', 'ANNOVAR_Ref', 'ANNOVAR_Alt'], how='left')
        df.drop(columns=['ANNOVAR_Chr', 'ANNOVAR_Start', 'ANNOVAR_End', 'ANNOVAR_Ref', 'ANNOVAR_Alt'], inplace=True)
        df = df.fillna('.')

        print(f'\nAnnovar analysis complete.\n')

    except Exception as e:
        print(f'\nWARNING: ANNOVAR annotation failed ({e}). '
              f'Filling {", ".join(ANNOVAR_COLUMNS)} with "fail" for all variants and continuing.\n')
        traceback.print_exc()
        for col in ANNOVAR_COLUMNS:
            df[col] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df


# Score one chunk of variants with a local CADD-scripts install (conda-only / -m mode)
def run_CADD_chunk(chunk_variants, idx, outprefix, CADD_script, CADD_data_dir, include_CADD_annotations):

    work_dir = os.path.dirname(outprefix)
    CADD_dir = os.path.join(work_dir, 'CADD', f'CADD_chunk_{idx}')
    os.makedirs(CADD_dir, exist_ok=True)
    vcf_path = os.path.join(CADD_dir, f'CADD_chunk_{idx}.vcf')
    vcf_gz_path = vcf_path + '.gz'
    for p in (vcf_path, vcf_gz_path):
        if os.path.exists(p):
            os.remove(p)

    with open(vcf_path, 'w') as f:
        for chrom, pos, ref, alt in chunk_variants:
            f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')
    subprocess.run(['bgzip', vcf_path])

    out_gz = os.path.join(CADD_dir, f'CADD_chunk_{idx}.tsv.gz')

    cmd = [CADD_script, '-m']
    if include_CADD_annotations:
        cmd.append('-a')
    cmd += ['-c', '1', '-o', out_gz, '-p', vcf_gz_path]

    log_file = os.path.join(CADD_dir, f'CADD_chunk_{idx}.log')

    CADD_install_dir = os.path.dirname(os.path.abspath(CADD_script))

    with open(log_file, 'w') as log:
        log.write(f'\n=== Attempt: conda-only (-m) ===\ncmd: {cmd}\ncwd: {CADD_install_dir}\n')
        log.flush()
        try:
            subprocess.run(cmd, stdout=log, stderr=log, check=True, cwd=CADD_install_dir)
        except subprocess.CalledProcessError:
            with open(log_file) as f:
                tail = ''.join(f.readlines()[-40:])
            raise RuntimeError(
                f'{CADD_script} failed for chunk {idx} in conda-only (-m) mode. '
                f'Last lines of {log_file}:\n{tail}')

    df_CADD = pd.read_csv(os.path.join(CADD_dir, f'CADD_chunk_{idx}.tsv.gz'), sep='\t', skiprows=1)
    return df_CADD


# Boolean mask: which variants are rare/unknown enough and not excluded-by-CLNSIG to bother
# scoring with CADD/SpliceAI (shared by both, called separately with each tool's own thresholds)
def _gnomad_clnsig_filter_mask(df, gnomad_af_threshold, clnsig_filter):
    mask = pd.Series(True, index=df.index)
    if gnomad_af_threshold is not None and 'gnomAD_AF' in df.columns:
        gnomad_numeric = pd.to_numeric(df['gnomAD_AF'], errors='coerce')
        mask &= (gnomad_numeric <= gnomad_af_threshold) | df['gnomAD_AF'].isin(['.', 'fail'])
    if clnsig_filter is not None and 'CLNSIG' in df.columns:
        mask &= ~df['CLNSIG'].isin(clnsig_filter)
    return mask


# Log how many unique variants a CADD/SpliceAI filter mask kept, out of the total
def _print_filter_summary(label, df, mask, gnomad_af_threshold, clnsig_filter):

    unique_cols = ['chrom', 'pos', 'ref', 'alt']
    n_total = df[unique_cols].drop_duplicates().shape[0]
    n_selected = df.loc[mask, unique_cols].drop_duplicates().shape[0]

    af_desc = f'gnomAD AF <= {gnomad_af_threshold} (or unknown/failed)' if gnomad_af_threshold is not None else 'no gnomAD AF filter'
    clnsig_desc = f'CLNSIG not in {clnsig_filter}' if clnsig_filter else 'no CLNSIG filter'

    print(f'\nFiltering {n_total} unique variants for {label} analysis: {af_desc} and {clnsig_desc} '
          f'-> {n_selected} unique variants selected for {label}.')


# CADD source 1: run CADD-scripts locally, splitting the masked variant set across `threads`
# parallel chunks (see run_CADD_chunk)
def _run_CADD_local(df, outprefix, CADD_script, CADD_data_dir, include_CADD_annotations, mask, threads):

    print(f'\nPreparing variants for CADD analysis...')
    filtered_df = df[mask].copy()
    filtered_df['chrom'] = filtered_df['chrom'].str.replace(r'^chr', '', regex=True)
    filtered_variants = list(set(map(tuple, filtered_df[['chrom', 'pos', 'ref', 'alt']].values.tolist())))

    if not filtered_variants:
        print(f'\nNo variants left after filtering for CADD analysis. Skipping CADD analysis.')
        df['CADD_PHRED'] = '.'
        return df

    chunk_size = ceil(len(filtered_variants) / threads)
    chunked_variants = [filtered_variants[i:i + chunk_size] for i in range(0, len(filtered_variants), chunk_size)]

    print(f'Running CADD on {len(filtered_variants)} variants in {len(chunked_variants)} chunks '
          f'of {len(chunked_variants[0])} variants each, using {threads} threads...')
    del filtered_variants

    with concurrent.futures.ProcessPoolExecutor(max_workers=threads) as executor:
        futures = {
            executor.submit(run_CADD_chunk, chunk, idx, outprefix, CADD_script,
                             CADD_data_dir, include_CADD_annotations): idx
            for idx, chunk in enumerate(chunked_variants)
        }
        results = []
        for future in concurrent.futures.as_completed(futures):
            try:
                results.append(future.result())
                print(f'Chunk {futures[future]} processed successfully.')
            except Exception as e:
                print(f'Error processing chunk {futures[future]}: {e}')
                traceback.print_exc()

    if not results:
        raise RuntimeError('No chunks completed successfully.')

    df_CADD = pd.concat(results, ignore_index=True)
    df_CADD = df_CADD.add_prefix('CADD_')
    df_CADD['CADD_#Chrom'] = 'chr' + df_CADD['CADD_#Chrom'].astype(str)
    df_CADD['CADD_Pos'] = df_CADD['CADD_Pos'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD, left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_#Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_#Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore'])
    df = df.fillna('.')
    print(f'\nCADD analysis complete.\n')
    return df


# Query a local bgzip+tabix-indexed TSV, restricted to a BED's positions
def _query_local_tabix_tsv(path, bed_file, cwd, columns):
    cmd = ['tabix', path, '-R', bed_file]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                           universal_newlines=True, cwd=cwd)
    if proc.returncode != 0:
        raise RuntimeError(f'tabix failed while querying {path}: {(proc.stderr or "").strip()}')
    return pd.read_csv(io.StringIO(proc.stdout), sep='\t', header=None, names=columns, dtype=str)


# CADD source 2 (fallback): look up scores in the local pre-scored SNV/InDel files instead of
# running CADD itself; InDels get '.' if no local InDel file was configured
def _run_CADD_local_prescored(df, outprefix, CADD_local_prescored_snv, CADD_local_prescored_indel,
                               cache_dir, mask, threads):

    print(f'\nLooking up CADD scores from local pre-scored file(s)...')
    os.makedirs(cache_dir, exist_ok=True)

    filtered_df = df[mask].copy()
    filtered_df = filtered_df.drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    filtered_df['chrom'] = filtered_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True)
    is_snv = (filtered_df['ref'].str.len() == 1) & (filtered_df['alt'].str.len() == 1)
    snv_df, indel_df = filtered_df[is_snv], filtered_df[~is_snv]

    columns = ['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore', 'CADD_PHRED']
    results = []

    for label, subset_df, prescored_file in (('SNV', snv_df, CADD_local_prescored_snv),
                                               ('InDel', indel_df, CADD_local_prescored_indel)):
        if subset_df.empty:
            continue
        if not prescored_file:
            print(f'  No local pre-scored {label} file provided -- {len(subset_df)} {label} '
                  f'variant(s) will get "." from this stage.')
            continue

        print(f'  Looking up {len(subset_df)} {label} variant(s) against {prescored_file}...')
        bed_file = outprefix + f'_cadd_local_lookup_{label.lower()}_positions.bed'
        bed_df = pd.DataFrame({
            'chrom': subset_df['chrom'],
            'start': subset_df['pos'].astype(int) - 1,
            'end': subset_df['pos'].astype(int),
        }).drop_duplicates()
        bed_df.to_csv(bed_file, sep='\t', index=False, header=False)

        subset_result = _query_local_tabix_tsv(prescored_file, bed_file, cache_dir, columns)
        if not subset_result.empty:
            results.append(subset_result)

    if not results:
        print(f'\nNo local pre-scored CADD matches found for this variant set. '
              f'Filling CADD_PHRED with "." for all variants.\n')
        df['CADD_PHRED'] = '.'
        return df

    df_CADD = pd.concat(results, ignore_index=True).drop_duplicates(
        subset=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df_CADD['CADD_Chrom'] = 'chr' + df_CADD['CADD_Chrom'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD[['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_PHRED']],
                  left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df['CADD_PHRED'] = df['CADD_PHRED'].fillna('.').astype(str)
    n_matched = df.loc[df['CADD_PHRED'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nCADD local pre-scored lookup complete ({n_matched} unique variants matched).\n')
    return df


# CADD source 3 (last resort): tabix the public pre-scored SNV file remotely; no InDel coverage
def _run_CADD_remote_prescored(df, outprefix, CADD_prescored_url, cache_dir, mask, threads):

    print(f'\nLooking up CADD scores from the remote pre-scored SNV file...')
    os.makedirs(cache_dir, exist_ok=True)

    cadd_bed_file = outprefix + '_cadd_lookup_positions.bed'
    filtered_df = df[mask].drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    bed_df = pd.DataFrame({
        'chrom': filtered_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True),
        'start': filtered_df['pos'].astype(int) - 1,
        'end': filtered_df['pos'].astype(int),
    }).drop_duplicates()

    if bed_df.empty:
        print(f'\nNo variants left after filtering for CADD analysis. Skipping CADD analysis.')
        df['CADD_PHRED'] = '.'
        return df

    bed_df.to_csv(cadd_bed_file, sep='\t', index=False, header=False)

    tabix_stdout = _run_remote_tabix_with_retry(CADD_prescored_url, ['-R', cadd_bed_file], cwd=cache_dir,
                                                 label='CADD pre-scored lookup')
    df_CADD = pd.read_csv(
        io.StringIO(tabix_stdout), sep='\t', header=None,
        names=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore', 'CADD_PHRED'], dtype=str)

    if df_CADD.empty:
        print(f'\nNo pre-scored CADD matches found for this variant set (SNVs only -- '
              f'any InDels are expected to miss). Filling CADD_PHRED with "." for all variants.\n')
        df['CADD_PHRED'] = '.'
        return df

    df_CADD['CADD_Chrom'] = 'chr' + df_CADD['CADD_Chrom'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD[['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_PHRED']],
                  left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df['CADD_PHRED'] = df['CADD_PHRED'].fillna('.').astype(str)
    n_matched = df.loc[df['CADD_PHRED'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nCADD pre-scored SNV lookup complete ({n_matched} unique variants matched).\n')
    return df


# Orchestrate the CADD fallback chain: local run -> local pre-scored -> remote pre-scored -> 'fail'
def run_CADD(df, outprefix, cache_dir, CADD_script, CADD_data_dir,
             CADD_local_prescored_snv, CADD_local_prescored_indel, CADD_prescored_url,
             include_CADD_annotations, mask, threads):

    used_local_run = False
    if CADD_script:
        try:
            df = _run_CADD_local(df, outprefix, CADD_script, CADD_data_dir,
                                  include_CADD_annotations, mask, threads)
            used_local_run = True
        except Exception as e:
            print(f'\nWARNING: local CADD scoring failed ({e}).')
            traceback.print_exc()
    else:
        print(f'\nNo local CADD install configured (--CADD-script not set, or "remote" was '
              f'requested in config.yaml).')

    used_local_prescored = False
    if not used_local_run:
        if CADD_local_prescored_snv or CADD_local_prescored_indel:
            print(f'  Falling back to local pre-scored lookup...\n' if CADD_script else
                  f'  Using local pre-scored lookup...\n')
            try:
                df = _run_CADD_local_prescored(df, outprefix, CADD_local_prescored_snv,
                                                CADD_local_prescored_indel, cache_dir, mask, threads)
                used_local_prescored = True
            except Exception as e:
                print(f'\nWARNING: local CADD pre-scored lookup failed ({e}).')
                traceback.print_exc()
        else:
            print(f'  No local pre-scored CADD files configured either '
                  f'(--CADD-local-prescored-snv/--CADD-local-prescored-indel).')

    if not used_local_run and not used_local_prescored:
        if CADD_prescored_url:
            print(f'  Falling back to remote pre-scored SNV lookup...\n')
            try:
                df = _run_CADD_remote_prescored(df, outprefix, CADD_prescored_url, cache_dir, mask, threads)
            except Exception as e:
                print(f'\nWARNING: remote CADD pre-scored lookup failed ({e}). '
                      f'Filling CADD_PHRED with "fail" for all variants and continuing.\n')
                traceback.print_exc()
                df['CADD_PHRED'] = 'fail'
        else:
            print(f'  No --CADD-prescored-url configured either -- '
                  f'filling CADD_PHRED with "fail" for all variants and continuing.\n')
            df['CADD_PHRED'] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df


# Score one chunk of variants with the live spliceai tool
def run_SpliceAI_chunk(chunk_variants, idx, outprefix, genome, annotation_arg):

    work_dir = os.path.dirname(outprefix)
    SpliceAI_dir = os.path.join(work_dir, 'SpliceAI', f'SpliceAI_chunk_{idx}')
    os.makedirs(SpliceAI_dir, exist_ok=True)
    in_vcf = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}_in.vcf')
    out_vcf = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}_out.vcf')

    with open(in_vcf, 'w') as f:
        f.write('##fileformat=VCFv4.2\n')
        unique_contig = {chrom for chrom, _, _, _ in chunk_variants}
        for contig in unique_contig:
            f.write(f'##contig=<ID={contig}>\n')
        f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
        for chrom, pos, ref, alt in chunk_variants:
            f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')

    log_file = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}.log')
    env = os.environ.copy()
    env['OMP_NUM_THREADS'] = '1'
    with open(log_file, 'w') as log:
        try:
            subprocess.run(
                ['spliceai', '-I', in_vcf, '-O', out_vcf, '-R', genome, '-A', annotation_arg, '-M', '1'],
                stdout=log, stderr=log, check=True, env=env)
        except subprocess.CalledProcessError as e:
            log.flush()
            with open(log_file) as f:
                tail = ''.join(f.readlines()[-20:])
            raise RuntimeError(
                f'spliceai failed for chunk {idx} (exit {e.returncode}). '
                f'Last lines of {log_file}:\n{tail}') from e

    result = subprocess.run(
        ['bcftools', 'query', '-f', '%CHROM\t%POS\t%REF\t%ALT\t%INFO/SpliceAI\n', out_vcf],
        stdout=subprocess.PIPE, universal_newlines=True, check=True)
    df_chunk = pd.read_csv(
        io.StringIO(result.stdout), sep='\t', header=None,
        names=['chrom', 'pos', 'ref', 'alt', 'SpliceAI'], dtype=str)

    return df_chunk


# SpliceAI source 2 (fallback / --SpliceAI-force-prescored-lookup): look up scores in the
# precomputed SNV/InDel VCFs instead of running spliceai live
def _run_SpliceAI_prescored_lookup(df, outprefix, snv_vcf, indel_vcf, mask, cache_dir, threads):

    print(f'\nLooking up SpliceAI scores from precomputed VCF(s)...')

    filtered_df = df[mask].copy()
    filtered_df = filtered_df.drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    is_snv = (filtered_df['ref'].str.len() == 1) & (filtered_df['alt'].str.len() == 1)
    snv_df = filtered_df[is_snv]
    indel_df = filtered_df[~is_snv]

    format_string = '%CHROM\t%POS\t%REF\t%ALT\t%INFO/SpliceAI\n'
    results = []

    for label, subset_df, vcf in (('SNV', snv_df, snv_vcf), ('InDel', indel_df, indel_vcf)):
        if subset_df.empty:
            continue
        if not vcf:
            print(f'  No prescored {label} VCF provided -- {len(subset_df)} {label} '
                  f'variant(s) will get "." for SpliceAI.')
            continue

        print(f'  Looking up {len(subset_df)} {label} variant(s) against {vcf}...')
        subset_bed_file = outprefix + f'_spliceai_{label.lower()}_lookup_positions.bed'
        bed_df = pd.DataFrame({
            'chrom': subset_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True),
            'start': subset_df['pos'].astype(int) - 1,
            'end': subset_df['pos'].astype(int),
        }).drop_duplicates()
        bed_df.to_csv(subset_bed_file, sep='\t', index=False, header=False)

        query_stdout = _query_vcf_regions(vcf, subset_bed_file, format_string, threads, cache_dir)
        subset_result = pd.read_csv(
            io.StringIO(query_stdout), sep='\t', header=None,
            names=['chrom', 'pos', 'ref', 'alt', 'SpliceAI'], dtype=str)
        if not subset_result.empty:
            subset_result['chrom'] = 'chr' + subset_result['chrom'].astype(str)
            results.append(subset_result)

    if results:
        df_SpliceAI = pd.concat(results, ignore_index=True).drop_duplicates(
            subset=['chrom', 'pos', 'ref', 'alt'])
        df['pos'] = df['pos'].astype(str)
        df = df.merge(df_SpliceAI, on=['chrom', 'pos', 'ref', 'alt'], how='left')
    df['SpliceAI'] = df['SpliceAI'].fillna('.').astype(str) if 'SpliceAI' in df.columns else '.'

    n_annotated = df.loc[df['SpliceAI'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nSpliceAI prescored lookup complete ({n_annotated} unique variants matched).\n')
    return df


# SpliceAI source 1: run the live spliceai tool, splitting the masked variant set across
# `threads` parallel chunks (see run_SpliceAI_chunk); builds a custom annotation from --gtf
# when given, otherwise uses SpliceAI's own bundled grch37/grch38 annotation
def _run_SpliceAI_live(df, outprefix, genome, gtf, SpliceAI_annotation, mask, threads):

    print(f'\nPreparing variants for SpliceAI analysis...')

    if shutil.which('spliceai') is None:
        raise FileNotFoundError(
            "'spliceai' executable not found on PATH. Check that spliceai is installed "
            "in the active environment (e.g. `pip install spliceai`) -- see environment.yaml.")

    if gtf:
        annotation_arg = outprefix + '_spliceai_annotation.txt'
        print(f'  Building SpliceAI gene annotation from {gtf}...')
        process_gtf(gtf, annotation_arg)
    else:
        annotation_arg = SpliceAI_annotation

    variants = list(set(map(tuple, df[mask][['chrom', 'pos', 'ref', 'alt']].values.tolist())))
    if not variants:
        print(f'\nNo variants to run SpliceAI on. Skipping SpliceAI analysis.')
        df['SpliceAI'] = '.'
        return df

    chunk_size = ceil(len(variants) / threads)
    chunked_variants = [variants[i:i + chunk_size] for i in range(0, len(variants), chunk_size)]

    print(f'Running SpliceAI on {len(variants)} variants in {len(chunked_variants)} chunks '
          f'of {len(chunked_variants[0])} variants each, using {threads} threads...')
    del variants

    with concurrent.futures.ProcessPoolExecutor(max_workers=threads) as executor:
        futures = {
            executor.submit(run_SpliceAI_chunk, chunk, idx, outprefix, genome, annotation_arg): idx
            for idx, chunk in enumerate(chunked_variants)
        }
        results = []
        for future in concurrent.futures.as_completed(futures):
            try:
                results.append(future.result())
                print(f'Chunk {futures[future]} processed successfully.')
            except Exception as e:
                print(f'Error processing chunk {futures[future]}: {e}')
                traceback.print_exc()

    if not results:
        raise RuntimeError('No chunks completed successfully.')

    df_SpliceAI = pd.concat(results, ignore_index=True)

    df['pos'] = df['pos'].astype(str)
    df = df.merge(df_SpliceAI, on=['chrom', 'pos', 'ref', 'alt'], how='left')
    df['SpliceAI'] = df['SpliceAI'].fillna('.').astype(str)
    print(f'\nSpliceAI analysis complete.\n')
    return df


# Orchestrate the SpliceAI fallback chain: live run -> prescored lookup -> 'fail'
def run_SpliceAI(df, outprefix, genome, gtf, SpliceAI_annotation, snv_vcf, indel_vcf,
                  force_prescored_lookup, mask, cache_dir, threads):

    used_live = False
    if force_prescored_lookup:
        print(f'\n--SpliceAI-force-prescored-lookup set -- skipping live SpliceAI run.')
    elif genome:
        try:
            df = _run_SpliceAI_live(df, outprefix, genome, gtf, SpliceAI_annotation, mask, threads)
            used_live = True
        except Exception as e:
            print(f'\nWARNING: local SpliceAI run failed ({e}).')
            traceback.print_exc()
    else:
        print(f'\nGenome FASTA file not provided -- skipping live SpliceAI run.')

    if not used_live:
        if snv_vcf or indel_vcf:
            print(f'  Falling back to local prescored lookup...\n' if (genome and not force_prescored_lookup) else
                  f'  Using local prescored lookup...\n')
            try:
                df = _run_SpliceAI_prescored_lookup(df, outprefix, snv_vcf, indel_vcf,
                                                     mask, cache_dir, threads)
            except Exception as e:
                print(f'\nWARNING: SpliceAI prescored lookup failed ({e}). '
                      f'Filling SpliceAI with "fail" for all variants and continuing.\n')
                traceback.print_exc()
                df['SpliceAI'] = 'fail'
        else:
            print(f'  No --SpliceAI-prescored-snv-vcf/--SpliceAI-prescored-indel-vcf '
                  f'configured either -- filling SpliceAI with "fail" for all variants and continuing.\n')
            df['SpliceAI'] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df



# Read all input VCFs, merge into one variants df, then run whichever annotation steps
# were configured (gnomAD, ClinVar, gene overlap, ANNOVAR, CADD, SpliceAI), in that order
def main():

    print(f"\n\n\n******************************************************************************************")
    print(f"Compiling variants...")
    print(f"******************************************************************************************\n")

    args = parse_args()

    outdir = os.path.dirname(args.outprefix)
    os.makedirs(outdir, exist_ok=True)

    work_dir = os.path.join(outdir, 'work')
    os.makedirs(work_dir, exist_ok=True)
    work_prefix = os.path.join(work_dir, args.sample_name)

    gnomad_cache_dir = os.path.join(work_dir, 'gnomAD_remote')
    clinvar_cache_dir = os.path.join(work_dir, 'ClinVar_remote')
    cadd_remote_cache_dir = os.path.join(work_dir, 'CADD_remote')
    spliceai_remote_cache_dir = os.path.join(work_dir, 'SpliceAI_remote')

    vcf_name_map = {}
    if args.vcf_file_names:
        vcf_name_map = dict(enumerate(args.vcf_file_names))

    data = {}
    for i, vcf_file in enumerate(args.vcf_files):
        vcf_file_name = vcf_name_map.get(i, vcf_file.split('/')[-1].split('.')[0])
        data.update(process_vcf(vcf_file, vcf_file_name, args.bed, args.genome))

    total_variants = len(data)
    unique_variants = len({(chrom, pos, ref, alt) for (_, chrom, pos, ref, alt) in data.keys()})
    print(f'\nProcessed {total_variants} total variants ({unique_variants} unique variants) '
          f'from {len(args.vcf_files)} VCF files.\n')

    column_names = ['name', 'chrom', 'pos', 'ref', 'alt', 'qual', 'filter', 'info', 'format', 'value', 'GT', 'DP', 'VAF', 'PS']
    df = pd.DataFrame([(k[0], k[1], k[2], k[3], k[4], *v) for k, v in data.items()], columns=column_names)
    df.insert(0, 'sample', args.sample_name)
    df.to_csv(os.path.join(work_prefix + '_compiled_variants.tsv'), sep='\t', index=False)
    del data

    bed_file = work_prefix + '_variant_positions.bed'
    bed_df = pd.DataFrame({
        'chrom': df['chrom'].astype(str),
        'start': df['pos'].astype(int) - 1,
        'end': df['pos'].astype(int),
    }).drop_duplicates()
    bed_df.to_csv(bed_file, sep='\t', index=False, header=False)

    if args.gnomad_vcf:
        df = extract_gnomAD_AF(df, args.gnomad_vcf, work_prefix, bed_file, args.threads, gnomad_cache_dir,
                                gnomad_vcf_fallback=args.gnomad_vcf_fallback)

    if args.clinvar_vcf:
        df = extract_CLNSIG(df, args.clinvar_vcf, work_prefix, bed_file, args.threads, clinvar_cache_dir,
                             clinvar_vcf_fallback=args.clinvar_vcf_fallback)

    df = add_gene_overlap_column(df, args.bed)

    if args.ANNOVAR_dir:
        if not args.genome:
            print(f'\nGenome FASTA file not provided. Skipping Annovar analysis.')
        else:
            df = run_ANNOVAR(df, work_prefix, args.ANNOVAR_dir, args.genome)

    cadd_mask = _gnomad_clnsig_filter_mask(df, args.CADD_gnomadAF_threshold, args.CADD_CLNSIG_filter)
    spliceai_mask = _gnomad_clnsig_filter_mask(df, args.SpliceAI_gnomadAF_threshold, args.SpliceAI_CLNSIG_filter)
    _print_filter_summary('CADD', df, cadd_mask, args.CADD_gnomadAF_threshold, args.CADD_CLNSIG_filter)
    _print_filter_summary('SpliceAI', df, spliceai_mask, args.SpliceAI_gnomadAF_threshold, args.SpliceAI_CLNSIG_filter)

    if args.CADD_script or args.CADD_local_prescored_snv or args.CADD_local_prescored_indel or args.CADD_prescored_url:
        include_CADD = args.include_CADD_annotations if args.include_CADD_annotations else False
        df = run_CADD(df, work_prefix, cadd_remote_cache_dir, args.CADD_script, args.CADD_data_dir,
                      args.CADD_local_prescored_snv, args.CADD_local_prescored_indel,
                      args.CADD_prescored_url, include_CADD, cadd_mask, args.threads)

    if args.include_SpliceAI_scores:
        df = run_SpliceAI(df, work_prefix, args.genome, args.gtf, args.SpliceAI_annotation,
                           args.SpliceAI_prescored_snv_vcf, args.SpliceAI_prescored_indel_vcf,
                           args.SpliceAI_force_prescored_lookup,
                           spliceai_mask, spliceai_remote_cache_dir, args.threads)

    df.to_csv(args.outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    if os.path.isfile(args.outprefix + '_compiled_variants.tsv'):
        print(f'\nResults saved to {args.outprefix + "_compiled_variants.tsv"}')
        work_tsv = work_prefix + '_compiled_variants.tsv'
        if os.path.isfile(work_tsv):
            os.remove(work_tsv)
    else:
        print(f'\nERROR: Results file not found. Please check the output directory for errors.')
        return



if __name__ == '__main__':
    main()