#!/usr/bin/env python

# Author: Nicole DeBruyne (Lin Lab)
# Date: 2024.10.23
# Optimized: 2025

import argparse
import re
import pandas as pd
import numpy as np
import subprocess
import os
import shutil
import pysam
from collections import defaultdict
import io
import concurrent.futures
import time
from math import ceil

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Compile variants from multiple VCF files and add annotations "
                    "(gnomAD, ClinVar, Annovar, CADD, SpliceAI) into a single .tsv file. "
                    "Note that contigs in all VCF and BED files should be formatted as "
                    "'chr1', 'chr2', ..., 'chrX', 'chrY', 'chrM'. "
                    "Also note that insertions should be formatted as A>ATC (rather than ->TC), "
                    "deletions as AAAGT>A (rather than AAGT>-), and SNVs as A>T for compatibility "
                    "with CLINVAR and gnomAD VCF files.")
    parser.add_argument("--vcf-files", required=True, nargs="+", help="Paths to VCF files")
    parser.add_argument('--vcf-file-names', nargs="+",
        help="Names of VCF files. If not provided, the file name will be used.")
    parser.add_argument("--outprefix", required=True,
        help="Output prefix (including path, not including file extension)")
    parser.add_argument("--sample-name", required=True,
        help="Sample identifier, stamped into a 'sample' column in the output tsv(s) "
             "so downstream cross-sample merging doesn't need to add it separately.")
    parser.add_argument("--bed",
        help="Path to BED file. If provided, only variants in the BED file will be compiled.")
    parser.add_argument("--genome",
        help="Path to FASTA file for the reference genome. Required if --ANNOVAR or --SpliceAI is used.")
    parser.add_argument("--gtf",
        help="Path to GTF file to build SpliceAI's gene annotation from (via process_gtf), so "
             "SpliceAI scores against the same annotation version used elsewhere in this "
             "pipeline. If --include-SpliceAI-scores is used and no GTF is provided, falls "
             "back to SpliceAI's own bundled annotation, selected via --SpliceAI-annotation.")
    parser.add_argument("--gnomad-vcf",
        help="Path to gnomAD VCF file(s). If provided, maximum gnomAD allele frequencies will be "
             "included in the final output. If multiple VCF files are provided, they should be "
             "provided as a comma-separated list (e.g. --gnomad-vcf 'gnomad.vcf.gz,gnomad2.vcf.gz').")
    parser.add_argument("--gnomad-vcf-fallback",
        help="Comma-separated gnomAD VCF file(s)/URL(s) to retry against if --gnomad-vcf fails "
             "for any reason at runtime (missing/unindexed local file, a failed bcftools call, "
             "etc.). Typically the canonical public gnomAD URLs, so a broken/missing local "
             "install doesn't halt the pipeline. If omitted, or identical to --gnomad-vcf, no "
             "second attempt is made.")
    parser.add_argument("--clinvar-vcf",
        help="Path to ClinVar VCF file. If provided, CLNSIG annotations will be included in the final output.")
    parser.add_argument("--clinvar-vcf-fallback",
        help="ClinVar VCF file/URL to retry against if --clinvar-vcf fails for any reason at "
             "runtime (see --gnomad-vcf-fallback). If omitted, or identical to --clinvar-vcf, "
             "no second attempt is made.")
    parser.add_argument("--ANNOVAR-dir",
        help="Path to Annovar directory. If provided, Annovar gene annotations "
             "(Func, Gene, GeneDetail, ExonicFunc, AAChange) will be included in the final output.")
    parser.add_argument("--CADD-script",
        help="Path to an executable that runs CADD-scripts' CADD.sh in conda-only mode "
             "(CADD.sh -m -- see setup_resources.sh's CADD-scripts install section) rather than "
             "a Singularity container. Normally CADD_wrapper.sh (generated by setup_resources.sh "
             "alongside CADD.sh, at resources/CADD-scripts-1.7.1/CADD_wrapper.sh) rather than "
             "CADD.sh itself -- the wrapper takes care of environment-specific setup (e.g. "
             "making a suitable `snakemake` available on PATH for CADD.sh's own internal "
             "`snakemake --sdm conda ...` call, without leaking unrelated tooling that could "
             "confuse CADD.sh's own per-rule conda environments) so this script doesn't need to "
             "know anything about it. If provided (non-empty), a local CADD run is attempted "
             "first. If omitted/empty, or if the local run fails at runtime, falls back to "
             "--CADD-local-prescored-snv/--CADD-local-prescored-indel, then to "
             "--CADD-prescored-url (see below).")
    parser.add_argument("--CADD-data-dir",
        help="Path to CADD-scripts' downloaded annotation/prescored data directory "
             "(resources/CADD-scripts-1.7.1/data). Expected to live alongside --CADD-script "
             "as CADD-scripts' own <install_dir>/data (CADD.sh finds it relative to itself), "
             "so this is only used to sanity-check the install before running. Required if "
             "--CADD-script is given.")
    parser.add_argument("--CADD-local-prescored-snv",
        help="Path to CADD-scripts' downloaded local pre-scored whole-genome SNV file "
             "(resources/CADD-scripts-1.7.1/data/prescored/GRCh38_v1.7/no_anno/"
             "whole_genome_SNVs.tsv.gz, bgzip+tabix-indexed), queried locally and restricted "
             "to the variant positions being compiled -- covers SNVs only (not InDels). Used "
             "as the CADD source whenever --CADD-script isn't provided, or if a local CADD run "
             "is attempted but fails at runtime. Falls back to --CADD-prescored-url if this "
             "isn't provided, or if this lookup fails at runtime.")
    parser.add_argument("--CADD-local-prescored-indel",
        help="Path to CADD-scripts' downloaded local pre-scored gnomAD InDel file "
             "(resources/CADD-scripts-1.7.1/data/prescored/GRCh38_v1.7/no_anno/"
             "gnomad.genomes.r4.0.indel.tsv.gz, bgzip+tabix-indexed), queried locally, "
             "alongside --CADD-local-prescored-snv, whenever that stage runs -- see above. "
             "InDels get a CADD_PHRED of '.' if this isn't provided, since "
             "--CADD-prescored-url has no InDel coverage to fall back to either.")
    parser.add_argument("--CADD-prescored-url",
        help="URL to CADD's public pre-scored whole-genome SNV file (bgzip+tabix-indexed), "
             "queried remotely and restricted to the variant positions being compiled -- "
             "covers SNVs only (not InDels). Used as the last-resort CADD source: whenever "
             "--CADD-script isn't provided and neither --CADD-local-prescored-snv nor "
             "--CADD-local-prescored-indel is provided either, or if a local CADD run and/or "
             "the local pre-scored lookup are attempted but fail at runtime. Any InDel gets a "
             "CADD_PHRED of '.' whenever this ends up being the source actually used, since "
             "there's no remote InDel lookup.")
    parser.add_argument("--include-CADD-annotations", action='store_true',
        help="Include CADD annotations in the final output. Note: there are >100 columns of CADD annotations, so use caution.")
    parser.add_argument("--CADD-gnomadAF-threshold", type=float, default=1,
        help="Allele frequency threshold for CADD analysis (only run CADD on variants with max "
             "gnomad AF below this threshold, or unknown/'.').")
    parser.add_argument("--CADD-CLNSIG-filter", nargs="+",
        help="CLNSIG values to exclude from CADD analysis (ex: Benign, Likely_benign, Benign/Likely_benign).")
    parser.add_argument("--SpliceAI-gnomadAF-threshold", type=float, default=1,
        help="Allele frequency threshold for SpliceAI analysis (only run SpliceAI on variants "
             "with max gnomad AF below this threshold, or unknown/'.'). Independent of "
             "--CADD-gnomadAF-threshold -- set both to the same value to keep CADD and SpliceAI "
             "scoring the same variant subset, or different values to filter each independently.")
    parser.add_argument("--SpliceAI-CLNSIG-filter", nargs="+",
        help="CLNSIG values to exclude from SpliceAI analysis (ex: Benign, Likely_benign, "
             "Benign/Likely_benign). Independent of --CADD-CLNSIG-filter (see above).")
    parser.add_argument("--include-SpliceAI-scores", action='store_true',
        help="Include SpliceAI scores in the final output. Runs the actual spliceai tool "
             "(bioconda/pip package) on the variant set first, if --genome is provided -- "
             "practical because by this point in the pipeline the variant set is small "
             "(a targeted panel's worth, post gnomAD/ClinVar/ANNOVAR/CADD), not genome-wide. "
             "If --genome isn't provided, or the live run fails at runtime, falls back to "
             "--SpliceAI-prescored-snv-vcf/--SpliceAI-prescored-indel-vcf instead -- see those "
             "flags.")
    parser.add_argument("--SpliceAI-annotation", choices=['grch37', 'grch38'], default='grch38',
        help="SpliceAI annotation version to use if --gtf is not provided (default: grch38). "
             "If --gtf IS provided, that takes precedence over this. Only used for live "
             "scoring -- has no effect if a prescored VCF lookup is used instead (see below).")
    parser.add_argument("--SpliceAI-prescored-snv-vcf", default=None,
        help="Path or URL to a bgzip+tabix-indexed VCF of precomputed SpliceAI SNV scores "
             "(e.g. Illumina's spliceai_scores.masked.snv.hg38.vcf.gz -- see "
             "setup_resources.sh). Used as the SpliceAI source whenever --genome isn't "
             "provided, or if a live spliceai run is attempted but fails at runtime -- SNVs "
             "are looked up here, InDels are looked up in --SpliceAI-prescored-indel-vcf. If "
             "one of the two isn't given while the other is, that variant type gets '.' (no "
             "fallback for just the missing one -- by design, to keep results consistent "
             "within a run).")
    parser.add_argument("--SpliceAI-prescored-indel-vcf", default=None,
        help="Path or URL to a bgzip+tabix-indexed VCF of precomputed SpliceAI InDel scores "
             "(e.g. Illumina's spliceai_scores.masked.indel.hg38.vcf.gz). See "
             "--SpliceAI-prescored-snv-vcf for how this and that flag interact.")
    parser.add_argument("--SpliceAI-force-prescored-lookup", action='store_true',
        help="Skip the live spliceai run entirely, even if --genome is provided, and go "
             "straight to the prescored VCF lookup (--SpliceAI-prescored-snv-vcf/"
             "--SpliceAI-prescored-indel-vcf). Without this flag, live scoring is always "
             "attempted first if --genome is given, and the prescored VCFs are only used as a "
             "fallback if that live run fails at runtime -- this flag is for cases where you'd "
             "rather always skip the (slower, TensorFlow-based) live run outright, e.g. to save "
             "compute time when the prescored files are known to already cover your variant set. "
             "Has no effect if neither prescored VCF is provided -- falls through to '.' the "
             "same as an unconfigured, failed live run would.")
    parser.add_argument("--final-gnomadAF-threshold", type=float,
        help="Only keep variants with gnomAD allele frequency <= threshold.")
    parser.add_argument("--final-CLNSIG-filter", nargs="+",
        help="Remove variants with specified CLNSIG values (ex: Benign, Likely_benign, Benign/Likely_benign).")
    parser.add_argument("--final-CADD-phred-threshold", type=int,
        help="Only keep variants with CADD phred score >= threshold (or SpliceAI score < threshold, "
             "if --final-SpliceAI-threshold is set).")
    parser.add_argument("--final-SpliceAI-threshold", type=float,
        help="Only keep variants with SpliceAI score >= threshold (or CADD phred score < threshold, "
             "if --final-CADD-phred-threshold is set).")
    parser.add_argument("--final-DP-threshold", type=int,
        help="Only keep variants with depth (DP) >= threshold.")
    parser.add_argument("--final-AF-threshold", type=float,
        help="Only keep variants with allele frequency (AF/VAF) >= threshold.")
    parser.add_argument('--keep-CLNSIG', nargs="+",
        default=['Pathogenic', 'Likely_pathogenic', 'Pathogenic/Likely_pathogenic'],
        help='Keep variants with these CLNSIG values in the final output regardless of all other '
             'filters. Default keeps all pathogenic variants: Pathogenic, Likely_pathogenic, '
             'Pathogenic/Likely_pathogenic')
    parser.add_argument("--threads", type=int, default=1,
        help="Number of threads to use (for running CADD and SpliceAI).")
    return parser.parse_args()


def process_gtf(gtf, outfile):
    """Build a SpliceAI-compatible custom gene annotation file from a GTF.

    GTF coordinates are 1-based, but SpliceAI's own loader does
    `tx_starts = df['TX_START'].to_numpy() + 1` -- i.e. it expects START
    values to already be 0-based (matching its bundled grch37.txt/
    grch38.txt). So START gets -1 here; END needs no adjustment, since a
    0-based-exclusive end and a 1-based-inclusive end are numerically the
    same value.
    """
    df = pd.read_csv(gtf, sep='\t', comment='#',
                     names=["CHROM", "SOURCE", "FEATURE", "START", "END", "SCORE", "STRAND", "FRAME", "ATTRIBUTES"])
    df = df[df['FEATURE'] == 'exon']
    df['TRANSCRIPT_ID'] = df['ATTRIBUTES'].str.extract('transcript_id "(.*?)"')
    df = df[['CHROM', 'STRAND', 'START', 'END', 'TRANSCRIPT_ID']]
    df['START'] = df['START'].astype(int) - 1
    grouped_df = df.groupby(['TRANSCRIPT_ID', 'CHROM', 'STRAND'])
    output_df = grouped_df.agg(
        TX_START=('START', 'min'),
        TX_END=('END', 'max'),
        EXON_START=('START', lambda x: ','.join(map(str, sorted(x))) + ','),
        EXON_END=('END', lambda x: ','.join(map(str, sorted(x))) + ',')
    )
    output_df.reset_index(inplace=True)
    output_df.rename(columns={'TRANSCRIPT_ID': '#NAME'}, inplace=True)
    output_df.to_csv(outfile, sep='\t', index=False)


def _run_remote_bcftools_pipeline(view_cmd, query_cmd, max_retries=5, initial_delay=15, cwd=None, label=None,
                                   quiet_success=False):
    """Run `bcftools view ... | bcftools query ...` and return the query's stdout text.

    Remote gnomAD/ClinVar/SpliceAI VCFs stream directly over HTTP(S) via
    htslib's libcurl backend, which intermittently drops long-lived HTTP/2
    streams with "Error in the HTTP2 framing layer" -- a known, generic
    libcurl/HTTP2 issue (curl/curl#3750), not specific to this pipeline or
    to any one host. Retries with exponential backoff before giving up.

    Querying a remote file also makes htslib cache a local copy of the
    small .tbi/.csi index (not the VCF itself) in whatever directory the
    process runs from. `cwd` pins that to a predictable per-sample
    location instead, so concurrent per-sample jobs don't collide writing
    index-cache files into a shared directory.

    `label`, if given, tags the success/failure log lines (e.g. 'chunk
    5/1208') so multi-chunk callers can show which chunk succeeded and how
    many attempts it took.

    `quiet_success`, if True, skips the "Succeeded on attempt X/Y" line --
    useful for local (non-HTTP) queries, which never need a retry, so that
    line would just be noise. Failures still print regardless.
    """
    tag = f' ({label})' if label else ''
    delay = initial_delay
    last_err = ''
    for attempt in range(1, max_retries + 1):
        view_proc = subprocess.Popen(view_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
        query_proc = subprocess.Popen(
            query_cmd, stdin=view_proc.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            universal_newlines=True, cwd=cwd)
        view_proc.stdout.close()
        query_out, query_err = query_proc.communicate()
        view_err = view_proc.stderr.read().decode(errors='replace') if view_proc.stderr else ''
        view_proc.wait()

        if view_proc.returncode == 0 and query_proc.returncode == 0:
            if not quiet_success:
                print(f'  Succeeded{tag} on attempt {attempt}/{max_retries}.')
            return query_out

        last_err = (view_err or query_err or '').strip()
        short_err = last_err.splitlines()[-1] if last_err else 'unknown error'
        if attempt < max_retries:
            print(f'  Remote VCF stream failed{tag} (attempt {attempt}/{max_retries}): {short_err}. '
                  f'Retrying in {delay}s...')
            time.sleep(delay)
            delay *= 2
        else:
            print(f'  Remote VCF stream failed{tag} (attempt {attempt}/{max_retries}): {short_err}. Giving up.')

    raise RuntimeError(
        f'bcftools failed after {max_retries} attempts while streaming remote VCF '
        f'({" ".join(view_cmd)}): {last_err}')


def _bcftools_header_with_retry(vcf_file, max_retries=5, initial_delay=15, cwd=None):
    """subprocess.check_output(['bcftools', 'view', '-h', vcf_file]) with retry,
    to survive the same transient remote-streaming errors as
    _run_remote_bcftools_pipeline (see docstring there). `cwd` is passed through
    for the same local-index-cache-location reason described there."""
    delay = initial_delay
    last_err = None
    for attempt in range(1, max_retries + 1):
        try:
            return subprocess.check_output(["bcftools", "view", "-h", vcf_file], text=True, cwd=cwd)
        except subprocess.CalledProcessError as e:
            last_err = e
            if attempt < max_retries:
                print(f'  Fetching header failed (attempt {attempt}/{max_retries}). Retrying in {delay}s...')
                time.sleep(delay)
                delay *= 2
    raise last_err


def _run_remote_tabix_with_retry(url, extra_args, max_retries=5, initial_delay=15, cwd=None, label=None):
    """tabix <url> <extra_args...> with retry, to survive the same transient
    remote-streaming errors as _run_remote_bcftools_pipeline (see docstring
    there). Returns stdout text. `cwd` pins tabix's local index-cache
    (.tbi) write to a predictable directory, same reasoning as
    _run_remote_bcftools_pipeline/_bcftools_header_with_retry.

    `label`, if given, is included in the log lines (see
    _run_remote_bcftools_pipeline). Success is always logged here (unlike
    _run_remote_bcftools_pipeline's quiet_success option) -- this function
    is only ever used for genuinely remote queries (CADD's pre-scored SNV
    lookup), so knowing which attempt it took is useful the same way it is
    for gnomAD/ClinVar.
    """
    tag = f' ({label})' if label else ''
    cmd = ['tabix', url] + list(extra_args)
    delay = initial_delay
    last_err = ''
    for attempt in range(1, max_retries + 1):
        proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               universal_newlines=True, cwd=cwd)
        if proc.returncode == 0:
            print(f'  Succeeded{tag} on attempt {attempt}/{max_retries}.')
            return proc.stdout
        last_err = (proc.stderr or '').strip()
        short_err = last_err.splitlines()[-1] if last_err else 'unknown error'
        if attempt < max_retries:
            print(f'  Remote tabix query failed{tag} (attempt {attempt}/{max_retries}): {short_err}. '
                  f'Retrying in {delay}s...')
            time.sleep(delay)
            delay *= 2
        else:
            print(f'  Remote tabix query failed{tag} (attempt {attempt}/{max_retries}): {short_err}. Giving up.')
    raise RuntimeError(f'tabix failed after {max_retries} attempts while querying {url}: {last_err}')


def _is_remote_url(path):
    return re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', path) is not None


def _query_vcf_regions(vcf_file, bed_file, format_string, threads, cwd, chunk_size=10, max_workers=None):
    """bcftools view -R bed_file <vcf_file> | bcftools query -f format_string,
    returning the combined stdout text.

    For a *remote* vcf_file, regions are split into chunks of `chunk_size`
    (default 10) and queried as separate connections, to work around a
    known htslib/libcurl HTTP/2 bug ("Error in the HTTP2 framing layer",
    curl/curl#3750). Chunk size matters empirically -- 10 keeps the
    per-attempt failure rate low; larger chunks (e.g. 100) fail more often,
    likely because a bigger connection streams more data/frames. A failed
    chunk only has to retry that chunk, not the whole panel.

    Pass chunk_size=None (or 0) to always query in one shot, even for a
    remote file -- useful when the remote file itself is small enough that
    one connection is unlikely to trip the bug (see extract_CLNSIG, whose
    ClinVar VCF is ~200MB vs. gnomAD's tens-of-GB-per-chromosome files).

    max_workers defaults to `threads` -- chunks are queried concurrently.
    Testing at max_workers=1 showed the same per-chunk retry pattern as
    parallel runs, so concurrency doesn't appear to affect the failure
    rate; there's no reason to pay for serial querying's longer wall-clock
    time. Every chunk's outcome (success or failure, and which attempt) is
    logged, so the retry rate stays visible if this needs re-tuning.

    Regions are deduped here too (belt-and-suspenders -- the real dedup
    happens once upstream, wherever bed_file is written, since df can have
    duplicate positions: one row per caller that reported a variant there,
    or per ALT at a multiallelic site). Cheap on an already-clean file,
    and guards against any future caller that forgets to dedupe first.

    Local vcf_file paths are always queried in one shot, since this bug is
    specific to remote HTTP(S)/FTP streaming.
    """
    if max_workers is None:
        max_workers = threads

    view_base_cmd = ['bcftools', 'view', '--threads', str(threads)]
    query_cmd = ['bcftools', 'query', '-f', format_string]

    if not _is_remote_url(vcf_file):
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=None, quiet_success=True)

    # Past this point vcf_file is confirmed remote, so this is the one
    # place cache_dir needs to exist -- created lazily here so a purely
    # local run never touches this directory.
    os.makedirs(cwd, exist_ok=True)

    if not chunk_size:
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=cwd)

    with open(bed_file) as fh:
        regions = sorted(set(line for line in fh if line.strip()))

    if len(regions) <= chunk_size:
        return _run_remote_bcftools_pipeline(
            view_base_cmd + ['-R', bed_file, vcf_file], query_cmd, cwd=cwd)

    chunks = [regions[i:i + chunk_size] for i in range(0, len(regions), chunk_size)]
    n_chunks = len(chunks)
    print(f'  {len(regions)} unique regions against a remote file -- querying in '
          f'{n_chunks} chunk(s) of {chunk_size} region(s) each, up to {max_workers} at a '
          f'time, to avoid a known libcurl HTTP/2 bug triggered by too many requests on '
          f'one persistent connection.')

    # Each chunk is tiny, so there's nothing worth parallel-decompressing
    # per chunk -- concurrency comes from running multiple chunks at once
    # instead (below). Using the full `threads` count here too would mean
    # threads*max_workers OS threads for a handful of bytes per chunk.
    chunk_view_cmd = ['bcftools', 'view', '--threads', '1']

    def _query_chunk(chunk_num, chunk_regions):
        chunk_bed = os.path.join(cwd, f'_region_chunk_{chunk_num}.bed')
        with open(chunk_bed, 'w') as fh:
            fh.writelines(chunk_regions)
        return chunk_num, _run_remote_bcftools_pipeline(
            chunk_view_cmd + ['-R', chunk_bed, vcf_file], query_cmd, cwd=cwd,
            label=f'chunk {chunk_num}/{n_chunks}')

    results = {}
    completed = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {
            executor.submit(_query_chunk, i + 1, chunk): i + 1
            for i, chunk in enumerate(chunks)
        }
        for future in concurrent.futures.as_completed(futures):
            chunk_num, stdout = future.result()
            results[chunk_num] = stdout
            completed += 1
            if completed % max(1, n_chunks // 10) == 0 or completed == n_chunks:
                print(f'  Completed {completed}/{n_chunks} chunks...')

    return ''.join(results[i + 1] for i in range(n_chunks))


def process_vcf(vcf_file, vcf_file_name, bed_file, genome):
    """Extract variant information from VCF file."""

    vcf_data = {}

    if not os.path.isfile(vcf_file):
        print(f'\nWARNING: VCF file {vcf_file} does not exist. Skipping...')
        return vcf_data

    if bed_file:
        command = ['bcftools', 'view', '-H', '-R', bed_file, '-e', 'GT="0/0" || GT="./."', vcf_file]
    else:
        command = ['bcftools', 'view', '-H', '-e', 'GT="0/0" || GT="./."', vcf_file]
    result = subprocess.run(command, stdout=subprocess.PIPE, universal_newlines=True, check=True)
    lines = result.stdout.split('\n')

    for line in lines[:-1]:   # skip trailing empty element
        fields = line.split('\t')
        chrom, pos, _, ref, alt, qual, filt, info, form, genotype = (f.strip() for f in fields[:10])
        format_keys = form.split(':')
        genotype_values = genotype.split(':')
        format_dict = dict(zip(format_keys, genotype_values))
        gt = format_dict.get('GT', '.')
        dp = format_dict.get('DP', '.')
        af = format_dict.get('VAF') or format_dict.get('AF') or '.'
        vcf_data[(vcf_file_name, chrom, pos, ref, alt)] = [qual, filt, info, form, genotype, gt, dp, af]

    print(f'\nFinished processing {len(vcf_data)} variants from {vcf_file}.')
    return vcf_data


def extract_gnomAD_AF(df, gnomad_vcf, outprefix, bed_file, threads, cache_dir, gnomad_vcf_fallback=None):
    """Extract gnomAD allele frequencies from gnomAD VCF file(s). Each entry in
    gnomad_vcf may be a local path or a remote http(s)/ftp URL -- a remote
    bgzip+tabix-indexed VCF is queried directly for only the byte ranges
    needed, never downloaded in full. Local-file/index existence is only
    checked for local paths, since remote index files are fetched
    transparently.

    cache_dir: where to pin htslib's local index-cache (.tbi/.csi) writes
    for remote queries (see _run_remote_bcftools_pipeline).

    gnomad_vcf_fallback: retried once if gnomad_vcf fails for any reason
    and isn't identical to gnomad_vcf -- typically the canonical public
    gnomAD URL, so a broken/missing local install doesn't halt the
    pipeline. If that also fails (or isn't given), 'gnomAD_AF' is filled
    with 'fail' for every variant instead of raising, so the rest of the
    pipeline still runs and the output always has this column. ('fail'
    is distinct from '.', which means the query ran successfully but the
    variant genuinely isn't in gnomAD.)
    """

    start_time = time.time()

    def is_remote(path):
        return re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', path) is not None

    def _attempt(gnomad_vcf_value):
        """One attempt against a given comma-separated gnomad_vcf value.
        Returns the updated df, or raises on any failure."""
        nonlocal df

        for gnomad_vcf_file in gnomad_vcf_value.split(','):
            gnomad_vcf_file = gnomad_vcf_file.strip()
            if is_remote(gnomad_vcf_file):
                continue
            if not os.path.isfile(gnomad_vcf_file):
                raise FileNotFoundError(f'gnomAD VCF file {gnomad_vcf_file} not found.')
            if not os.path.isfile(f'{gnomad_vcf_file}.csi') and not os.path.isfile(f'{gnomad_vcf_file}.tbi'):
                raise FileNotFoundError(f'gnomAD VCF file {gnomad_vcf_file} is not indexed.')

        af_chunks = []
        for gnomad_vcf_file in gnomad_vcf_value.split(','):
            gnomad_vcf_file = gnomad_vcf_file.strip()
            print(f'\nProcessing gnomAD VCF file: {gnomad_vcf_file}')
            print(f'  Extracting gnomAD allele frequencies from gnomAD VCF. This may take a few minutes...')

            file_is_remote = is_remote(gnomad_vcf_file)
            file_cwd = None
            if file_is_remote:
                os.makedirs(cache_dir, exist_ok=True)
                file_cwd = cache_dir

            header = _bcftools_header_with_retry(gnomad_vcf_file, cwd=file_cwd)
            if "ID=AF_grpmax" in header:
                af_tag = "AF_grpmax"
            elif "ID=AF_hom" in header:
                af_tag = "AF_hom"
            elif "ID=AF" in header:
                af_tag = "AF"
            else:
                print(f'  No AF field found in {gnomad_vcf_file}, skipping')
                continue

            format_string = f'%CHROM\t%POS\t%REF\t%ALT\t%INFO/{af_tag}\n'
            query_stdout = _query_vcf_regions(gnomad_vcf_file, bed_file, format_string, threads, cache_dir)
            af_df_subset = pd.read_csv(
                io.StringIO(query_stdout),
                sep='\t', header=None,
                names=['chrom', 'pos', 'ref', 'alt', 'gnomAD_AF'], dtype=str)

            # Vectorised AF parsing — avoids per-row apply
            def _parse_af_series(series):
                # Replace '.' with NaN, then take first comma-separated value
                s = series.where(series != '.', other=np.nan)
                s = s.str.split(',').str[0]
                return pd.to_numeric(s, errors='coerce')

            af_df_subset['gnomAD_AF'] = _parse_af_series(af_df_subset['gnomAD_AF'])
            if not af_df_subset.empty:
                af_chunks.append(af_df_subset)

        if af_chunks:
            af_df = pd.concat(af_chunks, ignore_index=True)
            af_df = af_df.groupby(['chrom', 'pos', 'ref', 'alt'], as_index=False)['gnomAD_AF'].max()
            df = df.merge(af_df[['chrom', 'pos', 'ref', 'alt', 'gnomAD_AF']],
                          on=['chrom', 'pos', 'ref', 'alt'], how='left')
        df['gnomAD_AF'] = df['gnomAD_AF'].fillna('.').astype(str) if 'gnomAD_AF' in df.columns else '.'

    try:
        _attempt(gnomad_vcf)
    except Exception as e:
        print(f'\nWARNING: gnomAD annotation failed ({e}).')
        if gnomad_vcf_fallback and gnomad_vcf_fallback.strip() != gnomad_vcf.strip():
            print(f'  Retrying against fallback source: {gnomad_vcf_fallback}\n')
            try:
                _attempt(gnomad_vcf_fallback)
            except Exception as e2:
                print(f'\nWARNING: gnomAD fallback also failed ({e2}). '
                      f'Filling gnomAD_AF with "fail" for all variants and continuing.\n')
                df['gnomAD_AF'] = 'fail'
        else:
            print(f'  No (different) fallback source available. '
                  f'Filling gnomAD_AF with "fail" for all variants and continuing.\n')
            df['gnomAD_AF'] = 'fail'

    if os.path.exists(outprefix + '_compiled_variants.tsv'):
        os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    print(f'\ngnomAD allele frequencies extracted for {df[df["gnomAD_AF"] != "."].shape[0]} '
          f'variants from gnomAD VCF in {time.time() - start_time:.2f} seconds.\n')
    return df


def extract_CLNSIG(df, clinvar_vcf, outprefix, bed_file, threads, cache_dir, clinvar_vcf_fallback=None):
    """Extract ClinVar CLNSIG annotations from ClinVar VCF file. clinvar_vcf may
    be a local path or a remote http(s)/ftp URL (see extract_gnomAD_AF).

    cache_dir: where to pin htslib's local index-cache writes for remote
    queries (see extract_gnomAD_AF / _run_remote_bcftools_pipeline).

    clinvar_vcf_fallback: retried once if clinvar_vcf fails and isn't
    identical to clinvar_vcf -- typically the canonical public ClinVar URL.
    If that also fails (or isn't given), 'CLNSIG' is filled with 'fail'
    for every variant instead of raising, so the rest of the pipeline
    still runs and the output always has this column. ('fail' is distinct
    from '.', which means the query ran successfully but the variant
    genuinely isn't in ClinVar.)
    """

    start_time = time.time()

    # ClinVar's VCF uses bare Ensembl-style contig names ("19", not
    # "chr19") -- confirmed directly (see test_remote_annotation_access.sh)
    # -- even though the rest of this pipeline, including bed_file, is
    # chr-prefixed. True for both local and remote ClinVar, since both come
    # from the same NCBI file. Querying with the chr-prefixed bed_file
    # directly returns zero matches silently, so build a chr-stripped copy
    # here (same pattern as _run_CADD_remote_prescored's cadd_bed_file).
    clinvar_bed_file = outprefix + '_clinvar_lookup_positions.bed'
    clinvar_bed_df = pd.read_csv(bed_file, sep='\t', header=None, names=['chrom', 'start', 'end'], dtype=str)
    clinvar_bed_df['chrom'] = clinvar_bed_df['chrom'].str.replace(r'^chr', '', regex=True)
    clinvar_bed_df.to_csv(clinvar_bed_file, sep='\t', index=False, header=False)

    def _attempt(clinvar_vcf_value):
        """One attempt against a given ClinVar VCF value. Raises on failure."""
        nonlocal df

        if not re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*://', clinvar_vcf_value):
            if not os.path.isfile(clinvar_vcf_value):
                raise FileNotFoundError(f'ClinVar VCF file {clinvar_vcf_value} not found.')
            if not os.path.isfile(f'{clinvar_vcf_value}.csi') and not os.path.isfile(f'{clinvar_vcf_value}.tbi'):
                raise FileNotFoundError(f'ClinVar VCF file {clinvar_vcf_value} is not indexed.')

        print(f'\nExtracting ClinVar CLNSIG annotations from ClinVar VCF. This may take a few minutes...')
        format_string = '%CHROM\t%POS\t%REF\t%ALT\t%INFO/CLNSIG\t%INFO/CLNSIGCONF\n'
        query_stdout = _query_vcf_regions(clinvar_vcf_value, clinvar_bed_file, format_string, threads, cache_dir,
                                           chunk_size=None)

        clnsig_df = pd.read_csv(
            io.StringIO(query_stdout),
            sep='\t', header=None,
            names=['chrom', 'pos', 'ref', 'alt', 'CLNSIG', 'CLNSIGCONF'], dtype=str)
        # Add the 'chr' prefix back so this merges correctly against df's
        # chr-prefixed chrom column.
        clnsig_df['chrom'] = 'chr' + clnsig_df['chrom'].astype(str)
        clnsig_df['CLNSIG'] = np.where(
            clnsig_df['CLNSIGCONF'].notna() & (clnsig_df['CLNSIGCONF'] != '.'),
            clnsig_df['CLNSIG'] + ':' + clnsig_df['CLNSIGCONF'],
            clnsig_df['CLNSIG']
        )
        df = df.merge(clnsig_df[['chrom', 'pos', 'ref', 'alt', 'CLNSIG']],
                      on=['chrom', 'pos', 'ref', 'alt'], how='left')
        df['CLNSIG'] = df['CLNSIG'].fillna('.').astype(str)

    try:
        _attempt(clinvar_vcf)
    except Exception as e:
        print(f'\nWARNING: ClinVar annotation failed ({e}).')
        if clinvar_vcf_fallback and clinvar_vcf_fallback.strip() != clinvar_vcf.strip():
            print(f'  Retrying against fallback source: {clinvar_vcf_fallback}\n')
            try:
                _attempt(clinvar_vcf_fallback)
            except Exception as e2:
                print(f'\nWARNING: ClinVar fallback also failed ({e2}). '
                      f'Filling CLNSIG with "fail" for all variants and continuing.\n')
                df['CLNSIG'] = 'fail'
        else:
            print(f'  No (different) fallback source available. '
                  f'Filling CLNSIG with "fail" for all variants and continuing.\n')
            df['CLNSIG'] = 'fail'

    if os.path.exists(outprefix + '_compiled_variants.tsv'):
        os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    print(f'ClinVar CLNSIG annotations extracted for {df[df["CLNSIG"] != "."].shape[0]} '
          f'variants from ClinVar VCF in {time.time() - start_time:.2f} seconds.\n')
    return df


def add_gene_overlap_column(df, panel_bed):
    """Add a 'gene' column listing every BED-panel gene whose interval overlaps
    each variant's position (comma-separated if more than one gene overlaps,
    '.' if none). Reads the panel BED the same way phase_reads.py's
    extract_gene_regions() does (chrom, start, end, gene name in column 4),
    so variant-level gene labels agree with the gene labels ASE/junction hits
    are already keyed on -- independent of ANNOVAR, whose refGene symbol can
    differ from the panel's own gene naming, or be unavailable entirely (see
    merge_hits.py, which uses this column -- not ANNOVAR_Gene.refGene -- to
    group variants by gene)."""
    if not panel_bed:
        df['gene'] = '.'
        return df

    genes_by_chrom = defaultdict(list)
    with open(panel_bed) as fh:
        for line in fh:
            fields = line.rstrip('\n').split('\t')
            chrom, start, end, gene = fields[0], int(fields[1]), int(fields[2]), fields[3]
            genes_by_chrom[chrom].append((start, end, gene))

    def genes_at(chrom, pos):
        # BED is 0-based half-open; pos here is 1-based (matches df['pos']).
        hits = [gene for start, end, gene in genes_by_chrom.get(chrom, []) if start < pos <= end]
        return ','.join(hits) if hits else '.'

    df['gene'] = [genes_at(chrom, int(pos)) for chrom, pos in zip(df['chrom'], df['pos'])]
    return df


def run_ANNOVAR(df, outprefix, ANNOVAR_dir, genome):
    """Run Annovar on all variants.

    If ANNOVAR fails for any reason (a failed convert2annovar.pl/
    table_annovar.pl call, an unreadable output file, etc.), the
    ANNOVAR_* columns are filled with 'fail' for every variant instead of
    raising, so the rest of the pipeline still runs and the output always
    has these columns. ('fail' is distinct from '.', which is used for
    variants ANNOVAR did successfully process but had no annotation for.)"""

    ANNOVAR_COLUMNS = [
        'ANNOVAR_Func.refGene', 'ANNOVAR_Gene.refGene', 'ANNOVAR_GeneDetail.refGene',
        'ANNOVAR_ExonicFunc.refGene', 'ANNOVAR_AAChange.refGene',
    ]

    try:
        ANNOVAR_outdir = os.path.join(os.path.dirname(outprefix), 'ANNOVAR')
        os.makedirs(ANNOVAR_outdir, exist_ok=True)
        print(f'\nMaking a VCF file with all variants for Annovar analysis...')
        # Use a set of tuples for deduplication — avoids itertuples overhead on large DFs
        variants = set(map(tuple, df[['chrom', 'pos', 'ref', 'alt']].values.tolist()))
        with open(os.path.join(ANNOVAR_outdir, 'compiled_variants.vcf'), 'w') as f:
            f.write('##fileformat=VCFv4.2\n')
            unique_contig = {chrom for chrom, _, _, _ in variants}
            for contig in unique_contig:
                f.write(f'##contig=<ID={contig}>\n')
            f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
            for chrom, pos, ref, alt in variants:
                f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')

        print(f'\nRunning Annovar on compiled variants...')
        log_file = os.path.join(ANNOVAR_outdir, 'ANNOVAR.log')
        with open(log_file, 'w') as log:
            subprocess.run(
                ['perl', os.path.join(ANNOVAR_dir, 'convert2annovar.pl'), '--format', 'vcf4',
                 os.path.join(ANNOVAR_outdir, 'compiled_variants.vcf'),
                 '--outfile', os.path.join(ANNOVAR_outdir, 'compiled_variants.avinput')],
                stdout=log, stderr=log, check=True)
            subprocess.run(
                ['perl', os.path.join(ANNOVAR_dir, 'table_annovar.pl'),
                 os.path.join(ANNOVAR_outdir, 'compiled_variants.avinput'),
                 os.path.join(ANNOVAR_dir, 'humandb'),
                 '-buildver', 'hg38', '-out', os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR'),
                 '-remove', '-protocol', 'refGene', '-operation', 'g', '-nastring', '.', '-csvout'],
                stdout=log, stderr=log, check=True)

        pysam_genome = pysam.FastaFile(genome)
        corrected_path = os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR.hg38_multianno_corrected.csv')
        with open(os.path.join(ANNOVAR_outdir, 'compiled_variants_ANNOVAR.hg38_multianno.csv'), 'r') as f, \
             open(corrected_path, 'w') as f2:
            for i, line in enumerate(f):
                if i == 0:
                    f2.write(line)
                    continue
                parts = line.strip().split(',')
                chrom, start, end, ref, alt = parts[0:5]
                if ref == '-':   # Insertion
                    pos = int(start)
                    ref = pysam_genome.fetch(chrom, pos - 1, pos)
                    alt = ref + alt
                elif alt == '-':  # Deletion
                    pos = int(start) - 1
                    alt = pysam_genome.fetch(chrom, pos - 1, pos)
                    ref = pysam_genome.fetch(chrom, pos - 1, pos + (int(end) - int(start)) + 1)
                else:             # SNP
                    pos = int(start)
                f2.write(f'{chrom},{pos},{end},{ref},{alt},' + ','.join(parts[5:]) + '\n')

        df_ANNOVAR = pd.read_csv(corrected_path, sep=',')
        df_ANNOVAR = df_ANNOVAR.add_prefix('ANNOVAR_')
        df_ANNOVAR['ANNOVAR_Start'] = df_ANNOVAR['ANNOVAR_Start'].astype(str)
        df['pos'] = df['pos'].astype(str)
        df = df.merge(df_ANNOVAR, left_on=['chrom', 'pos', 'ref', 'alt'],
                      right_on=['ANNOVAR_Chr', 'ANNOVAR_Start', 'ANNOVAR_Ref', 'ANNOVAR_Alt'], how='left')
        df.drop(columns=['ANNOVAR_Chr', 'ANNOVAR_Start', 'ANNOVAR_End', 'ANNOVAR_Ref', 'ANNOVAR_Alt'], inplace=True)
        df = df.fillna('.')

        # Keep all of ANNOVAR's raw output in ANNOVAR_outdir (input .vcf,
        # .avinput, .log, the raw multianno.csv, and the pipeline's
        # position-corrected version built above) rather than deleting the
        # intermediate files -- useful for debugging/audit.
        print(f'\nAnnovar analysis complete.\n')

    except Exception as e:
        print(f'\nWARNING: ANNOVAR annotation failed ({e}). '
              f'Filling {", ".join(ANNOVAR_COLUMNS)} with "fail" for all variants and continuing.\n')
        for col in ANNOVAR_COLUMNS:
            df[col] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df


def run_CADD_chunk(chunk_variants, idx, outprefix, CADD_script, CADD_data_dir, include_CADD_annotations):
    """Run CADD on a chunk of variants, via CADD-scripts' own conda envs.

    Invokes CADD_script directly (see setup_resources.sh's CADD-scripts
    install section). CADD_script is whatever config.yaml's cadd_script
    points at -- normally a wrapper script generated by setup_resources.sh
    (CADD_wrapper.sh, alongside CADD.sh itself), not CADD.sh directly.
    Environment requirements CADD.sh has (e.g. its conda mode needing
    Snakemake >=8.25.2 on PATH to launch its internal
    `snakemake --sdm conda ...` call, a version this pipeline's own
    Snakemake 7.x doesn't provide, without leaking other unrelated tooling
    onto PATH where it could shadow something CADD.sh's own per-rule conda
    envs need -- see setup_resources.sh's CADD-scripts section) are handled
    entirely by whatever config.yaml points cadd_script at, not by any
    environment-management logic here. This keeps compile_variants.py
    itself free of environment-specific assumptions, so it stays portable
    and runnable outside Snakemake too -- it just execs whatever
    CADD_script path it's given, inheriting its own environment as-is.

    Runs CADD.sh in conda-only mode (`-m`) directly -- singularity/
    apptainer is not attempted on this system.
    """

    # Grouped under {work_dir}/CADD/ rather than flat sibling files in
    # work/ -- work_dir is already sample-scoped, so a per-chunk sample
    # prefix would be redundant.
    work_dir = os.path.dirname(outprefix)
    CADD_dir = os.path.join(work_dir, 'CADD', f'CADD_chunk_{idx}')
    os.makedirs(CADD_dir, exist_ok=True)
    vcf_path = os.path.join(CADD_dir, f'CADD_chunk_{idx}.vcf')
    vcf_gz_path = vcf_path + '.gz'
    for p in (vcf_path, vcf_gz_path):
        if os.path.exists(p):
            os.remove(p)

    with open(vcf_path, 'w') as f:
        for chrom, pos, ref, alt in chunk_variants:
            f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')
    subprocess.run(['bgzip', vcf_path])

    # CADD.sh finds its data directory relative to its own location
    # (<CADD_script's dir>/data), so CADD_data_dir just needs to already be
    # that directory -- nothing to bind-mount for a local conda-based run.
    out_gz = os.path.join(CADD_dir, f'CADD_chunk_{idx}.tsv.gz')

    cmd = [CADD_script, '-m']
    if include_CADD_annotations:
        cmd.append('-a')
    cmd += ['-c', '1', '-o', out_gz, '-p', vcf_gz_path]

    log_file = os.path.join(CADD_dir, f'CADD_chunk_{idx}.log')

    # CADD.sh's *internal* Snakemake process (its own `--sdm conda ...`
    # call) resolves its own rules' relative data paths (e.g.
    # 'data/annotations/GRCh38_v1.7/esm/pep.110.fa') against whatever
    # directory it's actually launched from -- not against CADD.sh's own
    # script location, and not against CADD_data_dir. So this subprocess
    # MUST run with cwd set to CADD-scripts' own install directory
    # (wherever CADD_script/CADD_wrapper.sh itself lives), or every one of
    # those relative paths silently fails to resolve -- surfacing as a
    # Snakemake MissingInputException for rules further into CADD's own
    # DAG (e.g. annotate_esm), even though the files themselves are present
    # on disk. (CADD_dir, above, is this *pipeline's own* per-chunk work
    # directory -- unrelated, and wrong for this purpose despite the
    # similar name.) -o/-p above are absolute paths regardless, so they're
    # unaffected by this.
    CADD_install_dir = os.path.dirname(os.path.abspath(CADD_script))

    with open(log_file, 'w') as log:
        log.write(f'\n=== Attempt: conda-only (-m) ===\ncmd: {cmd}\ncwd: {CADD_install_dir}\n')
        log.flush()
        try:
            subprocess.run(cmd, stdout=log, stderr=log, check=True, cwd=CADD_install_dir)
        except subprocess.CalledProcessError:
            # Surface the log's tail so run_CADD's WARNING message shows
            # what actually went wrong, not just an exit code.
            with open(log_file) as f:
                tail = ''.join(f.readlines()[-40:])
            raise RuntimeError(
                f'{CADD_script} failed for chunk {idx} in conda-only (-m) mode. '
                f'Last lines of {log_file}:\n{tail}')

    df_CADD = pd.read_csv(os.path.join(CADD_dir, f'CADD_chunk_{idx}.tsv.gz'), sep='\t', skiprows=1)
    # Keep all of CADD's raw output for this chunk (input VCF, log, and the
    # CADD_chunk_{idx}.tsv.gz result) rather than deleting the intermediate
    # files -- useful for debugging/audit.
    return df_CADD


def _gnomad_clnsig_filter_mask(df, gnomad_af_threshold, clnsig_filter):
    """Boolean mask (aligned to df.index): True for variants passing a
    gnomAD-AF-threshold / CLNSIG-exclusion filter. Used to restrict which
    variants get sent to CADD (local or remote) and to SpliceAI -- each
    stage calls this with its own threshold/filter (--CADD-gnomadAF-
    threshold/--CADD-CLNSIG-filter vs. --SpliceAI-gnomadAF-threshold/
    --SpliceAI-CLNSIG-filter), so the two can be tuned to score different
    variant subsets, or set to matching values to always score the same one.

    Missing 'gnomAD_AF'/'CLNSIG' columns (source not provided at all) are
    treated as "no constraint from that source", not as excluding
    everything. Same for '.' (queried, genuinely not found/no value) and
    'fail' (the gnomAD stage itself failed at runtime) -- neither should
    cause a variant to be excluded just because its AF is unknown.
    """
    mask = pd.Series(True, index=df.index)
    if gnomad_af_threshold is not None and 'gnomAD_AF' in df.columns:
        gnomad_numeric = pd.to_numeric(df['gnomAD_AF'], errors='coerce')
        mask &= (gnomad_numeric <= gnomad_af_threshold) | df['gnomAD_AF'].isin(['.', 'fail'])
    if clnsig_filter is not None and 'CLNSIG' in df.columns:
        mask &= ~df['CLNSIG'].isin(clnsig_filter)
    return mask


def _print_filter_summary(label, df, mask, gnomad_af_threshold, clnsig_filter):
    """Prints a human-readable summary of a _gnomad_clnsig_filter_mask
    result -- what criteria were applied and how many UNIQUE variants
    (deduplicated by chrom/pos/ref/alt, same convention as
    _run_CADD_local/_run_SpliceAI_live's own variant counts) passed, out
    of how many unique variants total. Printed once for CADD's mask and
    once for SpliceAI's, right after both are computed in main() -- lets
    you directly compare the two selected counts before either stage
    actually runs, e.g. to confirm they're selecting the same variant set
    when --CADD-gnomadAF-threshold/--CADD-CLNSIG-filter and
    --SpliceAI-gnomadAF-threshold/--SpliceAI-CLNSIG-filter are configured
    to match. (Downstream per-stage counts can still differ from this
    even when the masks match exactly -- e.g. CADD's local-run vs.
    pre-scored-lookup tiers, or a prescored file simply not covering every
    selected variant -- but this isolates whether the *selection* itself
    matches, before any of that.)"""

    unique_cols = ['chrom', 'pos', 'ref', 'alt']
    n_total = df[unique_cols].drop_duplicates().shape[0]
    n_selected = df.loc[mask, unique_cols].drop_duplicates().shape[0]

    af_desc = f'gnomAD AF <= {gnomad_af_threshold} (or unknown/failed)' if gnomad_af_threshold is not None else 'no gnomAD AF filter'
    clnsig_desc = f'CLNSIG not in {clnsig_filter}' if clnsig_filter else 'no CLNSIG filter'

    print(f'\nFiltering {n_total} unique variants for {label} analysis: {af_desc} and {clnsig_desc} '
          f'-> {n_selected} unique variants selected for {label}.')


def _run_CADD_local(df, outprefix, CADD_script, CADD_data_dir, include_CADD_annotations, mask, threads):
    """Run CADD locally via CADD-scripts (CADD_script/CADD_data_dir), on
    variants passing `mask` (see _gnomad_clnsig_filter_mask). Raises on any
    failure rather than catching -- see run_CADD, the dispatcher that
    decides between this, the remote pre-scored lookup, and filling '.',
    and that does the checkpoint-tsv write either way.

    Assumes CADD-scripts' shared per-rule conda envs are already built
    (see setup_resources.sh's CADD-scripts section, which forces this via
    a real scoring pass against CADD-scripts' own bundled test VCF) --
    all chunks run concurrently from the start, with no serial
    first-chunk-alone step to build them. See run_CADD_chunk's chunk-
    submission comment below for what happens if that assumption doesn't
    hold."""

    print(f'\nPreparing variants for CADD analysis...')
    filtered_df = df[mask].copy()
    # Strip 'chr' prefix vectorially
    filtered_df['chrom'] = filtered_df['chrom'].str.replace(r'^chr', '', regex=True)
    filtered_variants = list(set(map(tuple, filtered_df[['chrom', 'pos', 'ref', 'alt']].values.tolist())))

    if not filtered_variants:
        print(f'\nNo variants left after filtering for CADD analysis. Skipping CADD analysis.')
        df['CADD_PHRED'] = '.'
        return df

    chunk_size = ceil(len(filtered_variants) / threads)
    chunked_variants = [filtered_variants[i:i + chunk_size] for i in range(0, len(filtered_variants), chunk_size)]

    print(f'Running CADD on {len(filtered_variants)} variants in {len(chunked_variants)} chunks '
          f'of {len(chunked_variants[0])} variants each, using {threads} threads...')
    del filtered_variants

    # Each chunk shells out to CADD_script, which runs CADD-scripts' conda
    # mode (see run_CADD_chunk), building/reusing shared per-rule conda
    # envs (under <CADD install dir>/envs/conda) via its internal
    # `snakemake --sdm conda ...` call. Those envs are assumed to already
    # be built at this point -- setup_resources.sh's CADD-scripts section
    # forces a real scoring pass against CADD-scripts' own bundled test
    # VCF specifically to build every env CADD.sh needs before any real
    # sample ever reaches this code path -- so all chunks (including the
    # first) run concurrently from the start, with no serial "build the
    # envs first" chunk. If that setup step was skipped, or a new env
    # somehow wasn't covered by it, concurrent chunks could race trying to
    # build the same missing env into the same shared --conda-prefix --
    # rerun setup_resources.sh's CADD-scripts section if that happens.
    with concurrent.futures.ProcessPoolExecutor(max_workers=threads) as executor:
        futures = {
            executor.submit(run_CADD_chunk, chunk, idx, outprefix, CADD_script,
                             CADD_data_dir, include_CADD_annotations): idx
            for idx, chunk in enumerate(chunked_variants)
        }
        results = []
        for future in concurrent.futures.as_completed(futures):
            try:
                results.append(future.result())
                print(f'Chunk {futures[future]} processed successfully.')
            except Exception as e:
                print(f'Error processing chunk {futures[future]}: {e}')

    if not results:
        raise RuntimeError('No chunks completed successfully.')

    df_CADD = pd.concat(results, ignore_index=True)
    # (CADD's raw per-chunk output now persists as CADD_chunk_{idx}.tsv.gz
    # under work/CADD/CADD_chunk_{idx}/ -- see run_CADD_chunk -- rather than
    # a separate combined file here.)
    df_CADD = df_CADD.add_prefix('CADD_')
    df_CADD['CADD_#Chrom'] = 'chr' + df_CADD['CADD_#Chrom'].astype(str)
    df_CADD['CADD_Pos'] = df_CADD['CADD_Pos'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD, left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_#Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_#Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore'])
    df = df.fillna('.')
    print(f'\nCADD analysis complete.\n')
    return df


def _query_local_tabix_tsv(path, bed_file, cwd, columns):
    """tabix <path> -R <bed_file>, run locally (no retry -- unlike the
    remote/URL case, a local file read failing isn't a transient network
    issue worth retrying). Returns a DataFrame parsed from stdout using
    `columns` as the (headerless) column names. Raises on any tabix
    failure."""
    cmd = ['tabix', path, '-R', bed_file]
    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                           universal_newlines=True, cwd=cwd)
    if proc.returncode != 0:
        raise RuntimeError(f'tabix failed while querying {path}: {(proc.stderr or "").strip()}')
    return pd.read_csv(io.StringIO(proc.stdout), sep='\t', header=None, names=columns, dtype=str)


def _run_CADD_local_prescored(df, outprefix, CADD_local_prescored_snv, CADD_local_prescored_indel,
                               cache_dir, mask, threads):
    """Look up CADD scores from CADD-scripts' own downloaded local
    pre-scored files (SNV and/or InDel) via a local tabix query,
    restricted to variants passing `mask` -- no local CADD-scripts *run*
    needed, just the downloaded prescored/ data. Each of
    CADD_local_prescored_snv/CADD_local_prescored_indel is optional: SNVs
    are looked up in the former, InDels in the latter; if one is missing,
    that variant type simply gets '.' from this stage (may still be
    covered by --CADD-prescored-url's remote SNV fallback afterwards, if
    it was an SNV). Raises on any failure -- see run_CADD, the dispatcher
    that decides between local run, this, the remote pre-scored lookup,
    and filling '.'."""

    print(f'\nLooking up CADD scores from local pre-scored file(s)...')
    os.makedirs(cache_dir, exist_ok=True)

    filtered_df = df[mask].copy()
    # Dedupe by (chrom, pos, ref, alt) before counting/looking up -- matches
    # _run_CADD_local's and _run_SpliceAI_live's variant counting (both use
    # set(map(tuple, ...))), so all three report/process a consistent
    # variant count regardless of duplicate rows in df (e.g. the same
    # variant surviving from more than one caller). Without this, a
    # duplicated row gets queried (and counted in the printed "Looking up N
    # variant(s)" message) once per occurrence -- harmless to the result
    # (same lookup, same score, merged back onto every duplicate row via
    # the final merge below regardless), but confusingly inconsistent
    # against SpliceAI's deduplicated count for the same mask/threshold.
    filtered_df = filtered_df.drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    # CADD's score files use bare Ensembl-style contig names ("19", not
    # "chr19") even on GRCh38 -- same convention as the remote lookup.
    filtered_df['chrom'] = filtered_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True)
    is_snv = (filtered_df['ref'].str.len() == 1) & (filtered_df['alt'].str.len() == 1)
    snv_df, indel_df = filtered_df[is_snv], filtered_df[~is_snv]

    columns = ['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore', 'CADD_PHRED']
    results = []

    for label, subset_df, prescored_file in (('SNV', snv_df, CADD_local_prescored_snv),
                                               ('InDel', indel_df, CADD_local_prescored_indel)):
        if subset_df.empty:
            continue
        if not prescored_file:
            print(f'  No local pre-scored {label} file provided -- {len(subset_df)} {label} '
                  f'variant(s) will get "." from this stage.')
            continue

        print(f'  Looking up {len(subset_df)} {label} variant(s) against {prescored_file}...')
        bed_file = outprefix + f'_cadd_local_lookup_{label.lower()}_positions.bed'
        bed_df = pd.DataFrame({
            'chrom': subset_df['chrom'],
            'start': subset_df['pos'].astype(int) - 1,
            'end': subset_df['pos'].astype(int),
        }).drop_duplicates()
        bed_df.to_csv(bed_file, sep='\t', index=False, header=False)

        subset_result = _query_local_tabix_tsv(prescored_file, bed_file, cache_dir, columns)
        if not subset_result.empty:
            results.append(subset_result)

    if not results:
        print(f'\nNo local pre-scored CADD matches found for this variant set. '
              f'Filling CADD_PHRED with "." for all variants.\n')
        df['CADD_PHRED'] = '.'
        return df

    df_CADD = pd.concat(results, ignore_index=True).drop_duplicates(
        subset=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df_CADD['CADD_Chrom'] = 'chr' + df_CADD['CADD_Chrom'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD[['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_PHRED']],
                  left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df['CADD_PHRED'] = df['CADD_PHRED'].fillna('.').astype(str)
    n_matched = df.loc[df['CADD_PHRED'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nCADD local pre-scored lookup complete ({n_matched} unique variants matched).\n')
    return df


def _run_CADD_remote_prescored(df, outprefix, CADD_prescored_url, cache_dir, mask, threads):
    """Look up CADD scores from the public pre-scored whole-genome SNV file
    via a remote tabix byte-range query, restricted to variants passing
    `mask` -- no local CADD-scripts install needed. SNVs only: any InDel,
    or any SNV simply not found, ends up '.' via the fillna below. Raises
    on any failure -- see run_CADD."""

    print(f'\nLooking up CADD scores from the remote pre-scored SNV file...')
    os.makedirs(cache_dir, exist_ok=True)

    # CADD's score files use bare Ensembl-style contig names ("19", not
    # "chr19") even on GRCh38 -- same convention as ClinVar.
    cadd_bed_file = outprefix + '_cadd_lookup_positions.bed'
    # Dedupe by (chrom, pos, ref, alt) first -- see _run_CADD_local_prescored's
    # matching comment. Doesn't change results (a duplicate row would just
    # query/merge the same score twice), but keeps this function's behavior
    # consistent with the other two CADD backends and avoids redundant work.
    filtered_df = df[mask].drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    bed_df = pd.DataFrame({
        'chrom': filtered_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True),
        'start': filtered_df['pos'].astype(int) - 1,
        'end': filtered_df['pos'].astype(int),
    }).drop_duplicates()

    if bed_df.empty:
        print(f'\nNo variants left after filtering for CADD analysis. Skipping CADD analysis.')
        df['CADD_PHRED'] = '.'
        return df

    bed_df.to_csv(cadd_bed_file, sep='\t', index=False, header=False)

    tabix_stdout = _run_remote_tabix_with_retry(CADD_prescored_url, ['-R', cadd_bed_file], cwd=cache_dir,
                                                 label='CADD pre-scored lookup')
    df_CADD = pd.read_csv(
        io.StringIO(tabix_stdout), sep='\t', header=None,
        names=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_RawScore', 'CADD_PHRED'], dtype=str)

    if df_CADD.empty:
        print(f'\nNo pre-scored CADD matches found for this variant set (SNVs only -- '
              f'any InDels are expected to miss). Filling CADD_PHRED with "." for all variants.\n')
        df['CADD_PHRED'] = '.'
        return df

    df_CADD['CADD_Chrom'] = 'chr' + df_CADD['CADD_Chrom'].astype(str)
    df['pos'] = df['pos'].astype(str)

    df = df.merge(df_CADD[['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt', 'CADD_PHRED']],
                  left_on=['chrom', 'pos', 'ref', 'alt'],
                  right_on=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'], how='left')
    df = df.drop(columns=['CADD_Chrom', 'CADD_Pos', 'CADD_Ref', 'CADD_Alt'])
    df['CADD_PHRED'] = df['CADD_PHRED'].fillna('.').astype(str)
    n_matched = df.loc[df['CADD_PHRED'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nCADD pre-scored SNV lookup complete ({n_matched} unique variants matched).\n')
    return df


def run_CADD(df, outprefix, cache_dir, CADD_script, CADD_data_dir,
             CADD_local_prescored_snv, CADD_local_prescored_indel, CADD_prescored_url,
             include_CADD_annotations, mask, threads):
    """Dispatcher: three-tier fallback.

    1. Local CADD-scripts scoring, if CADD_script is given (empty means
       not configured, or "remote" was requested in config.yaml --
       resolved upstream in the Snakefile/rule).
    2. Local pre-scored lookup (CADD_local_prescored_snv/
       CADD_local_prescored_indel), if step 1 wasn't attempted or failed
       at runtime.
    3. Remote pre-scored SNV lookup (CADD_prescored_url), if step 2 wasn't
       attempted (nothing configured) or failed at runtime -- SNVs only,
       so any InDel ends up '.' whenever this path is used.

    If none of the three are available/succeed, CADD_PHRED is filled with
    'fail' (distinct from '.', which means the lookup ran successfully but
    found no score for that variant) instead of raising, so the rest of
    the pipeline still runs.

    `mask` restricts which variants are sent to CADD -- all three tiers
    score the same passing subset, so switching between them doesn't
    change which variants get a score."""

    used_local_run = False
    if CADD_script:
        try:
            df = _run_CADD_local(df, outprefix, CADD_script, CADD_data_dir,
                                  include_CADD_annotations, mask, threads)
            used_local_run = True
        except Exception as e:
            print(f'\nWARNING: local CADD scoring failed ({e}).')
    else:
        print(f'\nNo local CADD install configured (--CADD-script not set, or "remote" was '
              f'requested in config.yaml).')

    used_local_prescored = False
    if not used_local_run:
        if CADD_local_prescored_snv or CADD_local_prescored_indel:
            print(f'  Falling back to local pre-scored lookup...\n' if CADD_script else
                  f'  Using local pre-scored lookup...\n')
            try:
                df = _run_CADD_local_prescored(df, outprefix, CADD_local_prescored_snv,
                                                CADD_local_prescored_indel, cache_dir, mask, threads)
                used_local_prescored = True
            except Exception as e:
                print(f'\nWARNING: local CADD pre-scored lookup failed ({e}).')
        else:
            print(f'  No local pre-scored CADD files configured either '
                  f'(--CADD-local-prescored-snv/--CADD-local-prescored-indel).')

    if not used_local_run and not used_local_prescored:
        if CADD_prescored_url:
            print(f'  Falling back to remote pre-scored SNV lookup...\n')
            try:
                df = _run_CADD_remote_prescored(df, outprefix, CADD_prescored_url, cache_dir, mask, threads)
            except Exception as e:
                print(f'\nWARNING: remote CADD pre-scored lookup failed ({e}). '
                      f'Filling CADD_PHRED with "fail" for all variants and continuing.\n')
                df['CADD_PHRED'] = 'fail'
        else:
            print(f'  No --CADD-prescored-url configured either -- '
                  f'filling CADD_PHRED with "fail" for all variants and continuing.\n')
            df['CADD_PHRED'] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df


def run_SpliceAI_chunk(chunk_variants, idx, outprefix, genome, annotation_arg):
    """Run the live spliceai tool on a chunk of variants."""

    # Grouped under {work_dir}/SpliceAI/ -- same convention as CADD's chunk dirs.
    work_dir = os.path.dirname(outprefix)
    SpliceAI_dir = os.path.join(work_dir, 'SpliceAI', f'SpliceAI_chunk_{idx}')
    os.makedirs(SpliceAI_dir, exist_ok=True)
    in_vcf = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}_in.vcf')
    out_vcf = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}_out.vcf')

    with open(in_vcf, 'w') as f:
        f.write('##fileformat=VCFv4.2\n')
        unique_contig = {chrom for chrom, _, _, _ in chunk_variants}
        for contig in unique_contig:
            f.write(f'##contig=<ID={contig}>\n')
        f.write('#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
        for chrom, pos, ref, alt in chunk_variants:
            f.write(f'{chrom}\t{pos}\t.\t{ref}\t{alt}\t.\t.\t.\n')

    log_file = os.path.join(SpliceAI_dir, f'SpliceAI_chunk_{idx}.log')
    env = os.environ.copy()
    # SpliceAI/TensorFlow uses all cores by default (via OpenMP), with no
    # flag to limit it. We're already running `threads` copies in parallel
    # (one per chunk), so pin each to one thread to avoid oversubscription
    # (see github.com/Illumina/SpliceAI/issues/20).
    env['OMP_NUM_THREADS'] = '1'
    with open(log_file, 'w') as log:
        try:
            subprocess.run(
                # -M 1: masked scores. Illumina's SpliceAI FAQ recommends
                # raw (-M 0, the default) for alternative splicing analysis
                # and masked for variant interpretation, which is what this
                # pipeline does -- masked zeroes out delta scores for
                # splicing changes that are typically much less pathogenic
                # (strengthening an annotated site, weakening an
                # unannotated one). Keep this consistent with any masked
                # precomputed-score lookup (see _run_SpliceAI_prescored_lookup) --
                # mixing masked and raw scores across samples would give
                # systematically different results, not just noisier ones.
                ['spliceai', '-I', in_vcf, '-O', out_vcf, '-R', genome, '-A', annotation_arg, '-M', '1'],
                stdout=log, stderr=log, check=True, env=env)
        except subprocess.CalledProcessError as e:
            # spliceai's actual error is in log_file, not this exception --
            # surface its tail so run_SpliceAI's error message shows what
            # actually went wrong, not just an exit code.
            log.flush()
            with open(log_file) as f:
                tail = ''.join(f.readlines()[-20:])
            raise RuntimeError(
                f'spliceai failed for chunk {idx} (exit {e.returncode}). '
                f'Last lines of {log_file}:\n{tail}') from e

    result = subprocess.run(
        ['bcftools', 'query', '-f', '%CHROM\t%POS\t%REF\t%ALT\t%INFO/SpliceAI\n', out_vcf],
        stdout=subprocess.PIPE, universal_newlines=True, check=True)
    df_chunk = pd.read_csv(
        io.StringIO(result.stdout), sep='\t', header=None,
        names=['chrom', 'pos', 'ref', 'alt', 'SpliceAI'], dtype=str)

    # Keep all of SpliceAI's raw output for this chunk (input VCF, log, and
    # the output VCF out_vcf) rather than deleting the intermediate files --
    # useful for debugging/audit (matches ANNOVAR_outdir / CADD's chunk dirs).
    return df_chunk


def _run_SpliceAI_prescored_lookup(df, outprefix, snv_vcf, indel_vcf, mask, cache_dir, threads):
    """Look up SpliceAI scores from precomputed SNV/InDel VCFs (e.g.
    Illumina's masked hg38 files -- see setup_resources.sh) for variants
    passing `mask`.

    snv_vcf/indel_vcf are each optional -- whichever is given is queried
    for that variant type; if only one is given, the other type gets '.'
    (no fallback for the missing one, by design, for consistency within a
    run). These files carry the same 'SpliceAI' INFO tag/format as the
    live tool's own output (Illumina generated them by running spliceai
    itself, genome-wide), so the same query format works for both.

    Uses _query_vcf_regions, so snv_vcf/indel_vcf may be local or remote --
    remote gets the same dedup/chunk/retry/logging as gnomAD/ClinVar.

    Uses bare Ensembl-style contig names ('1', not 'chr1') for the region
    query -- confirmed against the actual file (same convention as
    ClinVar/CADD's prescored files), despite the 'hg38' naming in
    Illumina's filenames suggesting UCSC/chr-prefixed style. df's own
    'chrom' column is chr-prefixed, so this is stripped for the query and
    re-added when merging results back.

    Raises on any failure rather than catching -- see run_SpliceAI, the
    dispatcher that decides between the live run, this, and filling '.',
    and that does the checkpoint-tsv write either way."""

    print(f'\nLooking up SpliceAI scores from precomputed VCF(s)...')

    filtered_df = df[mask].copy()
    # Dedupe by (chrom, pos, ref, alt) before counting/looking up -- matches
    # _run_SpliceAI_live's and both CADD prescored-lookup functions' variant
    # counting, so all of these report/process a consistent variant count
    # regardless of duplicate rows in df (e.g. the same variant surviving
    # from more than one caller). Without this, a duplicated row gets
    # queried (and counted in the printed "Looking up N variant(s)"
    # message) once per occurrence -- harmless to the result (same lookup,
    # same score, merged back onto every duplicate row via the final merge
    # below regardless), but confusingly inconsistent against the earlier
    # filter-summary count and against CADD's own (deduplicated) counts for
    # the same mask/threshold.
    filtered_df = filtered_df.drop_duplicates(subset=['chrom', 'pos', 'ref', 'alt'])
    is_snv = (filtered_df['ref'].str.len() == 1) & (filtered_df['alt'].str.len() == 1)
    snv_df = filtered_df[is_snv]
    indel_df = filtered_df[~is_snv]

    format_string = '%CHROM\t%POS\t%REF\t%ALT\t%INFO/SpliceAI\n'
    results = []

    for label, subset_df, vcf in (('SNV', snv_df, snv_vcf), ('InDel', indel_df, indel_vcf)):
        if subset_df.empty:
            continue
        if not vcf:
            print(f'  No prescored {label} VCF provided -- {len(subset_df)} {label} '
                  f'variant(s) will get "." for SpliceAI.')
            continue

        print(f'  Looking up {len(subset_df)} {label} variant(s) against {vcf}...')
        subset_bed_file = outprefix + f'_spliceai_{label.lower()}_lookup_positions.bed'
        bed_df = pd.DataFrame({
            'chrom': subset_df['chrom'].astype(str).str.replace(r'^chr', '', regex=True),
            'start': subset_df['pos'].astype(int) - 1,
            'end': subset_df['pos'].astype(int),
        }).drop_duplicates()
        bed_df.to_csv(subset_bed_file, sep='\t', index=False, header=False)

        query_stdout = _query_vcf_regions(vcf, subset_bed_file, format_string, threads, cache_dir)
        subset_result = pd.read_csv(
            io.StringIO(query_stdout), sep='\t', header=None,
            names=['chrom', 'pos', 'ref', 'alt', 'SpliceAI'], dtype=str)
        if not subset_result.empty:
            # Query used bare contig names to match the file; re-add 'chr'
            # so this merges correctly against df's own chr-prefixed 'chrom'.
            subset_result['chrom'] = 'chr' + subset_result['chrom'].astype(str)
            results.append(subset_result)

    if results:
        df_SpliceAI = pd.concat(results, ignore_index=True).drop_duplicates(
            subset=['chrom', 'pos', 'ref', 'alt'])
        df['pos'] = df['pos'].astype(str)
        df = df.merge(df_SpliceAI, on=['chrom', 'pos', 'ref', 'alt'], how='left')
    df['SpliceAI'] = df['SpliceAI'].fillna('.').astype(str) if 'SpliceAI' in df.columns else '.'

    n_annotated = df.loc[df['SpliceAI'] != '.', ['chrom', 'pos', 'ref', 'alt']].drop_duplicates().shape[0]
    print(f'\nSpliceAI prescored lookup complete ({n_annotated} unique variants matched).\n')
    return df


def _run_SpliceAI_live(df, outprefix, genome, gtf, SpliceAI_annotation, mask, threads):
    """Run the live spliceai tool on variants passing `mask` (see
    _gnomad_clnsig_filter_mask), in parallel chunks.

    Practical because by this point the variant set is small (a targeted
    panel's worth, post gnomAD/ClinVar/ANNOVAR/CADD filtering), not
    genome-wide -- same reasoning as live CADD scoring above. Uses its own
    --SpliceAI-gnomadAF-threshold/--SpliceAI-CLNSIG-filter, independent of
    CADD's, so the two stages can score different variant subsets if
    desired.

    Raises on any failure rather than catching -- see run_SpliceAI, the
    dispatcher that decides between this, the prescored lookup fallback,
    and filling '.', and that does the checkpoint-tsv write either way."""

    print(f'\nPreparing variants for SpliceAI analysis...')

    if shutil.which('spliceai') is None:
        raise FileNotFoundError(
            "'spliceai' executable not found on PATH. Check that spliceai is installed "
            "in the active environment (e.g. `pip install spliceai`) -- see environment.yaml.")

    if gtf:
        annotation_arg = outprefix + '_spliceai_annotation.txt'
        print(f'  Building SpliceAI gene annotation from {gtf}...')
        process_gtf(gtf, annotation_arg)
    else:
        annotation_arg = SpliceAI_annotation

    variants = list(set(map(tuple, df[mask][['chrom', 'pos', 'ref', 'alt']].values.tolist())))
    if not variants:
        print(f'\nNo variants to run SpliceAI on. Skipping SpliceAI analysis.')
        df['SpliceAI'] = '.'
        return df

    chunk_size = ceil(len(variants) / threads)
    chunked_variants = [variants[i:i + chunk_size] for i in range(0, len(variants), chunk_size)]

    print(f'Running SpliceAI on {len(variants)} variants in {len(chunked_variants)} chunks '
          f'of {len(chunked_variants[0])} variants each, using {threads} threads...')
    del variants

    with concurrent.futures.ProcessPoolExecutor(max_workers=threads) as executor:
        futures = {
            executor.submit(run_SpliceAI_chunk, chunk, idx, outprefix, genome, annotation_arg): idx
            for idx, chunk in enumerate(chunked_variants)
        }
        results = []
        for future in concurrent.futures.as_completed(futures):
            try:
                results.append(future.result())
                print(f'Chunk {futures[future]} processed successfully.')
            except Exception as e:
                print(f'Error processing chunk {futures[future]}: {e}')

    if not results:
        raise RuntimeError('No chunks completed successfully.')

    df_SpliceAI = pd.concat(results, ignore_index=True)
    # (SpliceAI's raw per-chunk output now persists as SpliceAI_chunk_{idx}_out.vcf
    # under work/SpliceAI/SpliceAI_chunk_{idx}/ -- see run_SpliceAI_chunk --
    # rather than a separate combined file here.)

    df['pos'] = df['pos'].astype(str)
    df = df.merge(df_SpliceAI, on=['chrom', 'pos', 'ref', 'alt'], how='left')
    df['SpliceAI'] = df['SpliceAI'].fillna('.').astype(str)
    print(f'\nSpliceAI analysis complete.\n')
    return df


def run_SpliceAI(df, outprefix, genome, gtf, SpliceAI_annotation, snv_vcf, indel_vcf,
                  force_prescored_lookup, mask, cache_dir, threads):
    """Dispatcher: try the live spliceai tool first if `genome` is given
    and force_prescored_lookup isn't set. If live isn't attempted (no
    genome, or force_prescored_lookup) or fails at runtime, fall back to
    the prescored VCF lookup (snv_vcf/indel_vcf -- see
    _run_SpliceAI_prescored_lookup). If both are unavailable/fail,
    'SpliceAI' is filled with 'fail' (distinct from '.', which means the
    run/lookup succeeded but found no score for that variant) instead of
    raising, so the rest of the pipeline still runs.

    force_prescored_lookup: skip the live run outright even if `genome`
    is given -- e.g. to always save the compute cost of live scoring when
    the prescored files are already known to cover the variant set,
    rather than only falling back to them on failure.

    `mask` restricts which variants are scored -- both backends score the
    same passing subset, so switching between them doesn't change which
    variants get a score."""

    used_live = False
    if force_prescored_lookup:
        print(f'\n--SpliceAI-force-prescored-lookup set -- skipping live SpliceAI run.')
    elif genome:
        try:
            df = _run_SpliceAI_live(df, outprefix, genome, gtf, SpliceAI_annotation, mask, threads)
            used_live = True
        except Exception as e:
            print(f'\nWARNING: local SpliceAI run failed ({e}).')
    else:
        print(f'\nGenome FASTA file not provided -- skipping live SpliceAI run.')

    if not used_live:
        if snv_vcf or indel_vcf:
            print(f'  Falling back to local prescored lookup...\n' if (genome and not force_prescored_lookup) else
                  f'  Using local prescored lookup...\n')
            try:
                df = _run_SpliceAI_prescored_lookup(df, outprefix, snv_vcf, indel_vcf,
                                                     mask, cache_dir, threads)
            except Exception as e:
                print(f'\nWARNING: SpliceAI prescored lookup failed ({e}). '
                      f'Filling SpliceAI with "fail" for all variants and continuing.\n')
                df['SpliceAI'] = 'fail'
        else:
            print(f'  No --SpliceAI-prescored-snv-vcf/--SpliceAI-prescored-indel-vcf '
                  f'configured either -- filling SpliceAI with "fail" for all variants and continuing.\n')
            df['SpliceAI'] = 'fail'

    os.remove(outprefix + '_compiled_variants.tsv')
    df.to_csv(outprefix + '_compiled_variants.tsv', sep='\t', index=False)
    return df


def filter_variants(input_df, args):
    """Filter variants based on user-defined criteria."""
    filtered_df = input_df.copy()

    if args.final_gnomadAF_threshold:
        if 'gnomAD_AF' not in filtered_df.columns:
            print(f"\nWARNING: gnomAD_AF column not found in DataFrame. Skipping filter.")
        else:
            gnomad_num = pd.to_numeric(filtered_df['gnomAD_AF'], errors='coerce')
            filtered_df = filtered_df[
                (gnomad_num <= args.final_gnomadAF_threshold) | filtered_df['gnomAD_AF'].isin(['.', 'fail'])
            ]

    if args.final_CLNSIG_filter:
        if 'CLNSIG' not in filtered_df.columns:
            print(f"\nWARNING: CLNSIG column not found in DataFrame. Skipping filter.")
        else:
            filtered_df = filtered_df[~filtered_df['CLNSIG'].isin(args.final_CLNSIG_filter)]

    if args.final_CADD_phred_threshold or args.final_SpliceAI_threshold:
        cadd_filtered_df = pd.DataFrame(columns=filtered_df.columns)
        spliceai_filtered_df = pd.DataFrame(columns=filtered_df.columns)

        if args.final_CADD_phred_threshold:
            if 'CADD_PHRED' not in filtered_df.columns:
                print(f"\nWARNING: CADD_PHRED column not found in DataFrame. Skipping CADD phred filter.")
            else:
                cadd_num = pd.to_numeric(filtered_df['CADD_PHRED'], errors='coerce')
                cadd_filtered_df = filtered_df[
                    (cadd_num >= args.final_CADD_phred_threshold) | filtered_df['CADD_PHRED'].isin(['.', 'fail'])
                ]

        if args.final_SpliceAI_threshold:
            if 'SpliceAI' not in filtered_df.columns:
                print(f"\nWARNING: SpliceAI column not found in DataFrame. Skipping SpliceAI filter.")
            else:
                thr = args.final_SpliceAI_threshold
                def _spliceai_pass(x):
                    if x in ('.', 'fail', '', None):
                        return True
                    return any(
                        pd.to_numeric(s, errors='coerce') >= thr
                        for s in str(x).split('|')[2:6]
                    )
                spliceai_filtered_df = filtered_df[filtered_df['SpliceAI'].apply(_spliceai_pass)]

        filtered_df = pd.concat([cadd_filtered_df, spliceai_filtered_df],
                                 ignore_index=True).drop_duplicates()

    if args.final_DP_threshold:
        if 'format' not in filtered_df.columns or 'value' not in filtered_df.columns:
            print(f"\nWARNING: format or value column not found in DataFrame. Skipping filter.")
        else:
            # Vectorised DP extraction
            def _dp_ok(row):
                fmt = row['format'].split(':')
                if 'DP' not in fmt:
                    return True
                val = row['value'].split(':')[fmt.index('DP')]
                dp = pd.to_numeric(val, errors='coerce')
                return pd.isna(dp) or dp >= args.final_DP_threshold
            filtered_df = filtered_df[filtered_df.apply(_dp_ok, axis=1)]

    if args.final_AF_threshold:
        if 'format' not in filtered_df.columns or 'value' not in filtered_df.columns:
            print(f"\nWARNING: format or value column not found in DataFrame. Skipping filter.")
        else:
            def _af_ok(row):
                fmt = row['format'].split(':')
                vals = row['value'].split(':')
                for tag in ('AF', 'VAF'):
                    if tag in fmt:
                        v = pd.to_numeric(vals[fmt.index(tag)], errors='coerce')
                        if not (pd.isna(v) or v >= args.final_AF_threshold):
                            return False
                return True
            filtered_df = filtered_df[filtered_df.apply(_af_ok, axis=1)]

    # Ensure variants with keep-CLNSIG values are preserved regardless of other filters
    def extract_CLNSIG_from_CLNSIGCONF(CLNSIG):
        if pd.isna(CLNSIG):
            return []
        if CLNSIG.startswith("Conflicting_classifications_of_pathogenicity:"):
            return [t.strip() for t in [x.split("(")[0] for x in CLNSIG.split(":", 1)[1].split("|")] if t.strip()]
        return [CLNSIG]

    if args.keep_CLNSIG:
        if 'CLNSIG' not in filtered_df.columns:
            print(f"\nWARNING: CLNSIG column not found in DataFrame. Skipping filter.")
        else:
            keep_set = set(args.keep_CLNSIG)
            keep_mask = input_df['CLNSIG'].apply(
                lambda x: any(term in keep_set for term in extract_CLNSIG_from_CLNSIGCONF(x))
            )
            keep_df = input_df[keep_mask].copy()
            filtered_df = pd.concat([filtered_df, keep_df]).drop_duplicates()

    return filtered_df


def main():
    """Main function."""

    print(f"\n\n\n******************************************************************************************")
    print(f"Compiling variants...")
    print(f"******************************************************************************************\n")

    args = parse_args()

    outdir = os.path.dirname(args.outprefix)
    os.makedirs(outdir, exist_ok=True)

    # All intermediate/checkpoint output goes under work/ rather than
    # alongside the final output. The annotation functions below just
    # write their checkpoint to whatever prefix they're handed and never
    # re-read from disk (the DataFrame passes through in memory), so
    # routing them at work_prefix instead of args.outprefix is enough.
    work_dir = os.path.join(outdir, 'work')
    os.makedirs(work_dir, exist_ok=True)
    work_prefix = os.path.join(work_dir, args.sample_name)

    # Per-tool subdirectories under work/, one per annotation source (see
    # run_ANNOVAR, run_CADD_chunk, run_SpliceAI_chunk for ANNOVAR/CADD/
    # SpliceAI's own dirs). "_remote" suffix on gnomAD/ClinVar/CADD/
    # SpliceAI's cache dirs: only created when a remote query is actually
    # made, so a purely local run never creates them. CADD_remote is
    # separate from CADD's own local-scoring dir since both can run in the
    # same sample (remote as a fallback).
    gnomad_cache_dir = os.path.join(work_dir, 'gnomAD_remote')
    clinvar_cache_dir = os.path.join(work_dir, 'ClinVar_remote')
    cadd_remote_cache_dir = os.path.join(work_dir, 'CADD_remote')
    spliceai_remote_cache_dir = os.path.join(work_dir, 'SpliceAI_remote')

    # Build a name→index map once to avoid repeated .index() calls
    vcf_name_map = {}
    if args.vcf_file_names:
        vcf_name_map = dict(enumerate(args.vcf_file_names))

    data = {}
    for i, vcf_file in enumerate(args.vcf_files):
        vcf_file_name = vcf_name_map.get(i, vcf_file.split('/')[-1].split('.')[0])
        data.update(process_vcf(vcf_file, vcf_file_name, args.bed, args.genome))

    total_variants = len(data)
    unique_variants = len({(chrom, pos, ref, alt) for (_, chrom, pos, ref, alt) in data.keys()})
    print(f'\nProcessed {total_variants} total variants ({unique_variants} unique variants) '
          f'from {len(args.vcf_files)} VCF files.\n')

    column_names = ['name', 'chrom', 'pos', 'ref', 'alt', 'qual', 'filter', 'info', 'format', 'value', 'GT', 'DP', 'VAF']
    df = pd.DataFrame([(k[0], k[1], k[2], k[3], k[4], *v) for k, v in data.items()], columns=column_names)
    df.insert(0, 'sample', args.sample_name)
    df.to_csv(os.path.join(work_prefix + '_compiled_variants.tsv'), sep='\t', index=False)
    del data

    # Write a BED of variant positions, deduped -- df has one row per
    # (caller, chrom, pos, ref, alt), so the same position can repeat
    # (called by multiple callers, or a multiallelic site). Dedup once
    # here so every consumer (extract_gnomAD_AF, extract_CLNSIG) gets a
    # clean region list.
    bed_file = work_prefix + '_variant_positions.bed'
    bed_df = pd.DataFrame({
        'chrom': df['chrom'].astype(str),
        'start': df['pos'].astype(int) - 1,
        'end': df['pos'].astype(int),
    }).drop_duplicates()
    bed_df.to_csv(bed_file, sep='\t', index=False, header=False)

    if args.gnomad_vcf:
        df = extract_gnomAD_AF(df, args.gnomad_vcf, work_prefix, bed_file, args.threads, gnomad_cache_dir,
                                gnomad_vcf_fallback=args.gnomad_vcf_fallback)

    if args.clinvar_vcf:
        df = extract_CLNSIG(df, args.clinvar_vcf, work_prefix, bed_file, args.threads, clinvar_cache_dir,
                             clinvar_vcf_fallback=args.clinvar_vcf_fallback)

    df = add_gene_overlap_column(df, args.bed)

    if args.ANNOVAR_dir:
        if not args.genome:
            print(f'\nGenome FASTA file not provided. Skipping Annovar analysis.')
        else:
            df = run_ANNOVAR(df, work_prefix, args.ANNOVAR_dir, args.genome)

    # Computed once each, after gnomAD/ClinVar have populated their
    # columns (if provided). CADD and SpliceAI each have their own
    # threshold/filter, so they can be tuned separately -- set both to the
    # same values to always score the same variant subset.
    cadd_mask = _gnomad_clnsig_filter_mask(df, args.CADD_gnomadAF_threshold, args.CADD_CLNSIG_filter)
    spliceai_mask = _gnomad_clnsig_filter_mask(df, args.SpliceAI_gnomadAF_threshold, args.SpliceAI_CLNSIG_filter)
    _print_filter_summary('CADD', df, cadd_mask, args.CADD_gnomadAF_threshold, args.CADD_CLNSIG_filter)
    _print_filter_summary('SpliceAI', df, spliceai_mask, args.SpliceAI_gnomadAF_threshold, args.SpliceAI_CLNSIG_filter)

    # Runs if any of the three CADD sources is available -- the dispatcher
    # itself decides which one(s) to actually use/fall back to (local run
    # -> local pre-scored lookup -> remote pre-scored lookup).
    if args.CADD_script or args.CADD_local_prescored_snv or args.CADD_local_prescored_indel or args.CADD_prescored_url:
        include_CADD = args.include_CADD_annotations if args.include_CADD_annotations else False
        df = run_CADD(df, work_prefix, cadd_remote_cache_dir, args.CADD_script, args.CADD_data_dir,
                      args.CADD_local_prescored_snv, args.CADD_local_prescored_indel,
                      args.CADD_prescored_url, include_CADD, cadd_mask, args.threads)

    if args.include_SpliceAI_scores:
        # Dispatcher decides between the live run (if --genome is given and
        # --SpliceAI-force-prescored-lookup isn't set) and the prescored
        # VCF lookup fallback (see run_SpliceAI's docstring).
        df = run_SpliceAI(df, work_prefix, args.genome, args.gtf, args.SpliceAI_annotation,
                           args.SpliceAI_prescored_snv_vcf, args.SpliceAI_prescored_indel_vcf,
                           args.SpliceAI_force_prescored_lookup,
                           spliceai_mask, spliceai_remote_cache_dir, args.threads)

    # All annotation stages are done -- this is the one and only write to the real,
    # final output location (everything above only ever touched work_prefix).
    df.to_csv(args.outprefix + '_compiled_variants.tsv', sep='\t', index=False)

    if os.path.isfile(args.outprefix + '_compiled_variants.tsv'):
        print(f'\nResults saved to {args.outprefix + "_compiled_variants.tsv"}')
        # The working checkpoint in work/ has served its purpose now that the
        # real final file is confirmed written -- remove it rather than leaving
        # a duplicate copy behind. (Only removed after confirming the final
        # write succeeded, so a failed write doesn't lose both copies.)
        work_tsv = work_prefix + '_compiled_variants.tsv'
        if os.path.isfile(work_tsv):
            os.remove(work_tsv)
    else:
        print(f'\nERROR: Results file not found. Please check the output directory for errors.')
        return

    if (args.final_gnomadAF_threshold or args.final_CLNSIG_filter or
            args.final_CADD_phred_threshold or args.final_DP_threshold or args.final_AF_threshold):
        print(f"\nFiltering variants...")
        filtered_df = filter_variants(df, args)
        filtered_df.to_csv(args.outprefix + '_filtered_variants.tsv', sep='\t', index=False)
        print(f"Filtered results written to: {args.outprefix + '_filtered_variants.tsv'}")


if __name__ == '__main__':
    main()